# Opta Shot Qualifier Audit

Scans every JSONP match file under `data/raw/PRD/2025-2026/matches/` and collects
every qualifier that appears on shot-type events (typeIds 13, 14, 15, 16).

**Goal:** Find qualifiers that appear on shots but are NOT in `data/mapping/opta-qualifiers.js`.

**Shot typeIds:**
- `13` — Miss (shot wide or over)
- `14` — Post (hits woodwork)
- `15` — Attempt Saved
- `16` — Goal

In [1]:
import json
import re
from pathlib import Path
from collections import defaultdict, Counter

import pandas as pd

ROOT        = Path("..")
MATCHES_DIR = ROOT / "data" / "raw" / "PRD" / "2025-2026" / "matches"
QUALS_JS    = ROOT / "data" / "mapping" / "opta-qualifiers.js"

SHOT_TYPE_IDS = {13, 14, 15, 16}
SHOT_TYPE_NAMES = {
    13: "Miss",
    14: "Post",
    15: "Attempt Saved",
    16: "Goal",
}

print(f"Matches dir    : {MATCHES_DIR.resolve()}")
print(f"  exists       : {MATCHES_DIR.exists()}")
print(f"Qualifiers JS  : {QUALS_JS.resolve()}")
print(f"  exists       : {QUALS_JS.exists()}")

Matches dir    : C:\Users\Usuario\OneDrive\football-analytics-research\data\raw\PRD\2025-2026\matches
  exists       : True
Qualifiers JS  : C:\Users\Usuario\OneDrive\football-analytics-research\data\mapping\opta-qualifiers.js
  exists       : True

In [2]:
# ── Load qualifier mapping from opta-qualifiers.js ───────────────────────────

def load_qualifiers_mapping(js_path: Path) -> dict[int, dict]:
    """
    Parse opta-qualifiers.js and return {qualifierId (int): {name, description}}.
    Uses same JS→JSON normalisation as the events mapping loader.
    """
    content = js_path.read_text(encoding="utf-8")

    match = re.search(r'var\s+\w+\s*=\s*(\{.*\});?', content, re.DOTALL)
    if not match:
        raise ValueError(f"Could not extract mapping dict from {js_path}")

    js_obj = match.group(1)
    js_obj = re.sub(r'(\w+):', r'"\1":', js_obj)   # quote all bare keys
    js_obj = re.sub(r"'([^']*?)'", r'"\1"', js_obj) # single → double quotes
    js_obj = re.sub(r',\s*\}', '}', js_obj)          # strip trailing commas

    raw = json.loads(js_obj)
    return {int(k): v for k, v in raw.items()}


def qual_name(qid: int, mapping: dict) -> str:
    if qid not in mapping:
        return "*** NOT IN MAPPING ***"
    entry = mapping[qid]
    return entry.get("name", str(qid)) if isinstance(entry, dict) else str(entry)


quals_mapping = load_qualifiers_mapping(QUALS_JS)
print(f"Loaded {len(quals_mapping)} qualifier entries from opta-qualifiers.js")
print("\nSample entries:")
for qid in [15, 20, 72, 108, 9, 214]:
    print(f"  {qid:>4}  {qual_name(qid, quals_mapping)}")

Loaded 273 qualifier entries from opta-qualifiers.js

Sample entries:
    15  Head
    20  Right footed
    72  Left footed
   108  Volley
     9  Penalty
   214  Big Chance

In [3]:
# ── JSONP helpers ─────────────────────────────────────────────────────────────

def extract_json_from_jsonp(path: Path) -> dict:
    raw = path.read_text(encoding="utf-8")
    start = raw.index("{")
    payload = raw[start:].rstrip()
    if payload.endswith(")"):
        payload = payload[:-1]
    return json.loads(payload)


# ── Scan all match files, collect shot events ─────────────────────────────────

def scan_shots(
    matches_dir: Path,
    shot_type_ids: set[int],
) -> list[dict]:
    """
    Walk every match file and return one dict per shot event with all qualifier IDs.
    """
    shots: list[dict] = []
    errors: list[str] = []

    all_files = sorted(
        p for p in matches_dir.iterdir()
        if p.is_file() and not p.name.startswith(".")
    )
    print(f"Found {len(all_files)} file(s) to scan...")

    for fp in all_files:
        try:
            data   = extract_json_from_jsonp(fp)
            events = data["liveData"]["event"]
        except Exception as exc:
            errors.append(f"{fp.name}: {exc}")
            continue

        for ev in events:
            tid = ev.get("typeId")
            if tid not in shot_type_ids:
                continue

            qualifier_ids = [q.get("qualifierId") for q in ev.get("qualifier", [])]
            qualifier_vals = {
                q.get("qualifierId"): q.get("value")
                for q in ev.get("qualifier", [])
            }

            shots.append({
                "match"         : fp.name,
                "type_id"       : tid,
                "type_name"     : SHOT_TYPE_NAMES.get(tid, str(tid)),
                "period"        : ev.get("periodId"),
                "minute"        : ev.get("timeMin"),
                "outcome"       : ev.get("outcome"),
                "x"             : ev.get("x"),
                "y"             : ev.get("y"),
                "qualifier_ids" : qualifier_ids,
                "qualifier_vals": qualifier_vals,
            })

    print(f"✓ Scanned {len(all_files) - len(errors)} files")
    print(f"✗ Errors  {len(errors)} files")
    if errors:
        for e in errors:
            print(f"  {e}")
    return shots


shots = scan_shots(MATCHES_DIR, SHOT_TYPE_IDS)

print(f"\nTotal shot events collected: {len(shots):,}")
print("\nBreakdown by type:")
for tid, name in SHOT_TYPE_NAMES.items():
    n = sum(1 for s in shots if s["type_id"] == tid)
    print(f"  typeId {tid:>2}  {name:<15}  {n:>5,}")

Found 230 file(s) to scan...
✓ Scanned 230 files
✗ Errors  0 files

Total shot events collected: 5,793

Breakdown by type:
  typeId 13  Miss             2,163
  typeId 14  Post                98
  typeId 15  Attempt Saved    2,927
  typeId 16  Goal               605

In [4]:
# ── Overall qualifier distribution across ALL shot events ─────────────────────

total_shots = len(shots)
all_qual_counts: Counter = Counter()
for s in shots:
    all_qual_counts.update(s["qualifier_ids"])

rows = []
for qid, cnt in all_qual_counts.most_common():
    rows.append({
        "qualifierId"  : qid,
        "name"         : qual_name(qid, quals_mapping),
        "occurrences"  : cnt,
        "pct_of_shots" : f"{cnt / total_shots * 100:.1f}%",
        "in_mapping"   : qid in quals_mapping,
    })

df_all_quals = pd.DataFrame(rows)
print(f"All qualifiers found on {total_shots:,} shot events ({len(all_qual_counts)} distinct qualifier IDs):\n")
display(df_all_quals)

All qualifiers found on 5,793 shot events (103 distinct qualifier IDs):

,qualifierId,name,occurrences,pct_of_shots,in_mapping
0,103,Goal mouth z co-ordinate,5793,100.0%,True
1,102,Goal mouth y co-ordinate,5793,100.0%,True
2,56,Zone,5793,100.0%,True
3,231,GK Y Coordinate,4434,76.5%,True
4,230,GK X Coordinate,4434,76.5%,True
...,...,...,...,...,...
98,358,*** NOT IN MAPPING ***,1,0.0%,False
99,484,*** NOT IN MAPPING ***,1,0.0%,False
100,459,*** NOT IN MAPPING ***,1,0.0%,False
101,490,*** NOT IN MAPPING ***,1,0.0%,False
102,474,*** NOT IN MAPPING ***,1,0.0%,False

In [5]:
# ── Qualifiers NOT in the mapping ─────────────────────────────────────────────

unknown = df_all_quals[~df_all_quals["in_mapping"]].copy()

if unknown.empty:
    print("✅  Every qualifier on shots is present in opta-qualifiers.js — nothing missing.")
else:
    print(f"🚨  {len(unknown)} qualifier(s) found on shots that are NOT in opta-qualifiers.js:\n")
    display(unknown)

    # For each unknown qualifier, show a few example events so we can reason about it
    MAX_EXAMPLES = 10
    for _, row in unknown.iterrows():
        qid = row["qualifierId"]
        print(f"\n{'─'*60}")
        print(f"  qualifierId {qid}  |  {row['occurrences']} occurrences on shots")
        print(f"{'─'*60}")

        examples = [
            s for s in shots
            if qid in s["qualifier_ids"]
        ][:MAX_EXAMPLES]

        # Which shot types carry this qualifier?
        type_dist = Counter(
            f"{s['type_id']} ({s['type_name']})"
            for s in shots
            if qid in s["qualifier_ids"]
        )
        print("\n  Shot types that carry this qualifier:")
        for label, cnt in type_dist.most_common():
            print(f"    {cnt:>4}x   {label}")

        # Value distribution (most qualifiers have no value, but some do)
        val_dist = Counter(
            s["qualifier_vals"].get(qid)
            for s in shots
            if qid in s["qualifier_ids"]
        )
        print("\n  Qualifier value distribution:")
        for val, cnt in val_dist.most_common(10):
            print(f"    {cnt:>4}x   {repr(val)}")

        # Co-occurring qualifiers (what else appears alongside this unknown qualifier?)
        cooccur: Counter = Counter()
        for s in shots:
            if qid in s["qualifier_ids"]:
                for other_qid in s["qualifier_ids"]:
                    if other_qid != qid:
                        cooccur[other_qid] += 1
        print("\n  Top co-occurring qualifiers:")
        for other_qid, cnt in cooccur.most_common(10):
            print(f"    {cnt:>4}x   qualifierId {other_qid}  ({qual_name(other_qid, quals_mapping)})")

        # Sample rows
        print(f"\n  Sample shots (up to {MAX_EXAMPLES}):")
        display(
            pd.DataFrame(examples)[[
                "match", "type_name", "period", "minute", "outcome", "x", "y", "qualifier_ids"
            ]]
        )

🚨  20 qualifier(s) found on shots that are NOT in opta-qualifiers.js:

     qualifierId                    name  occurrences pct_of_shots  in_mapping
20           458  *** NOT IN MAPPING ***         1502        25.9%       False
27           375  *** NOT IN MAPPING ***          605        10.4%       False
28           374  *** NOT IN MAPPING ***          605        10.4%       False
29           395  *** NOT IN MAPPING ***          598        10.3%       False
30           396  *** NOT IN MAPPING ***          598        10.3%       False
42           391  *** NOT IN MAPPING ***          255         4.4%       False
43           468  *** NOT IN MAPPING ***          243         4.2%       False
54           472  *** NOT IN MAPPING ***          116         2.0%       False
61           390  *** NOT IN MAPPING ***           85         1.5%       False
62           353  *** NOT IN MAPPING ***           85         1.5%       False
77           300  *** NOT IN MAPPING ***           28         0.5%       False
81           362  *** NOT IN MAPPING ***           21         0.4%       False
84           343  *** NOT IN MAPPING ***           16         0.3%       False
90           314  *** NOT IN MAPPING ***           11         0.2%       False
95           487  *** NOT IN MAPPING ***            3         0.1%       False
98           358  *** NOT IN MAPPING ***            1         0.0%       False
99           484  *** NOT IN MAPPING ***            1         0.0%       False
100          459  *** NOT IN MAPPING ***            1         0.0%       False
101          490  *** NOT IN MAPPING ***            1         0.0%       False
102          474  *** NOT IN MAPPING ***            1         0.0%       False

────────────────────────────────────────────────────────────
  qualifierId 458  |  1502 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     752x   15 (Attempt Saved)
     538x   13 (Miss)
     184x   16 (Goal)
      28x   14 (Post)

  Qualifier value distribution:
    1502x   None

  Top co-occurring qualifiers:
    1502x   qualifierId 103  (Goal mouth z co-ordinate)
    1502x   qualifierId 102  (Goal mouth y co-ordinate)
    1502x   qualifierId 56  (Zone)
    1204x   qualifierId 231  (GK Y Coordinate)
    1204x   qualifierId 230  (GK X Coordinate)
     870x   qualifierId 146  (Blocked x co-ordinate)
     870x   qualifierId 147  (Blocked y co-ordinate)
     847x   qualifierId 20  (Right footed)
     787x   qualifierId 22  (Regular play)
     724x   qualifierId 233  (Opposite related event ID)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Miss,1,4,1,77.2,55.8,"[328, 103, 215, 231, 102, 160, 230, 77, 72, 45..."
1,10d1132abu0fa9xolj05top3o,Attempt Saved,1,34,1,74.3,35.8,"[102, 328, 215, 103, 24, 146, 20, 82, 18, 233,..."
2,10d1132abu0fa9xolj05top3o,Attempt Saved,1,47,1,92.9,32.9,"[56, 102, 20, 233, 22, 147, 103, 78, 458, 328,..."
3,10d1132abu0fa9xolj05top3o,Attempt Saved,2,54,1,90.6,39.3,"[22, 15, 102, 328, 233, 56, 147, 458, 146, 103..."
4,10d1132abu0fa9xolj05top3o,Attempt Saved,2,61,1,90.2,48.5,"[146, 458, 147, 108, 103, 231, 233, 25, 17, 10..."
5,10d1132abu0fa9xolj05top3o,Attempt Saved,2,61,1,79.9,41.5,"[231, 102, 146, 458, 147, 215, 82, 230, 18, 56..."
6,10d1132abu0fa9xolj05top3o,Attempt Saved,2,74,1,92.0,42.7,"[146, 15, 214, 147, 102, 56, 22, 233, 328, 17,..."
7,10d1132abu0fa9xolj05top3o,Goal,2,74,1,96.2,54.6,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
8,10d1132abu0fa9xolj05top3o,Attempt Saved,2,80,1,76.6,31.1,"[18, 102, 146, 26, 103, 56, 458, 78, 147, 120,..."
9,10d1132abu0fa9xolj05top3o,Attempt Saved,2,92,1,96.8,69.5,"[20, 458, 147, 146, 22, 233, 102, 468, 103, 65..."

────────────────────────────────────────────────────────────
  qualifierId 375  |  605 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     605x   16 (Goal)

  Qualifier value distribution:
       1x   '74:13.610'
       1x   '63:51.548'
       1x   '76:31.092'
       1x   '89:08.876'
       1x   '08:28.091'
       1x   '10:59.852'
       1x   '41:27.192'
       1x   '60:02.740'
       1x   '09:37.687'
       1x   '33:39.653'

  Top co-occurring qualifiers:
     605x   qualifierId 374  (*** NOT IN MAPPING ***)
     605x   qualifierId 102  (Goal mouth y co-ordinate)
     605x   qualifierId 231  (GK Y Coordinate)
     605x   qualifierId 56  (Zone)
     605x   qualifierId 230  (GK X Coordinate)
     605x   qualifierId 103  (Goal mouth z co-ordinate)
     598x   qualifierId 395  (*** NOT IN MAPPING ***)
     598x   qualifierId 396  (*** NOT IN MAPPING ***)
     406x   qualifierId 29  (Assisted)
     406x   qualifierId 55  (Related event ID)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Goal,2,74,1,96.2,54.6,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,Goal,2,76,1,88.1,52.0,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,Goal,2,89,1,85.6,44.6,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,Goal,1,8,1,87.4,43.4,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,Goal,1,11,1,93.6,47.2,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,Goal,1,41,1,86.6,68.5,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,Goal,2,60,1,92.6,67.2,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,Goal,1,9,1,74.9,47.6,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,Goal,1,33,1,80.7,32.8,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

────────────────────────────────────────────────────────────
  qualifierId 374  |  605 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     605x   16 (Goal)

  Qualifier value distribution:
       1x   '2025-10-25 19:03:45.078'
       1x   '2025-11-01 16:40:20.541'
       1x   '2025-11-01 16:53:00.085'
       1x   '2025-11-01 17:05:37.869'
       1x   '2025-11-02 17:40:26.638'
       1x   '2025-11-02 17:42:58.399'
       1x   '2025-11-02 18:13:25.739'
       1x   '2025-11-02 18:51:35.387'
       1x   '2025-11-02 20:13:46.901'
       1x   '2025-11-02 20:37:48.867'

  Top co-occurring qualifiers:
     605x   qualifierId 375  (*** NOT IN MAPPING ***)
     605x   qualifierId 102  (Goal mouth y co-ordinate)
     605x   qualifierId 231  (GK Y Coordinate)
     605x   qualifierId 56  (Zone)
     605x   qualifierId 230  (GK X Coordinate)
     605x   qualifierId 103  (Goal mouth z co-ordinate)
     598x   qualifierId 395  (*** NOT IN MAPPING ***)
     598x   qualifierId 396  (*** NOT IN MAPPING ***)
     406x   qualifierId 29  (Assisted)
     406x   qualifierId 55  (Related event ID)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Goal,2,74,1,96.2,54.6,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,Goal,2,76,1,88.1,52.0,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,Goal,2,89,1,85.6,44.6,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,Goal,1,8,1,87.4,43.4,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,Goal,1,11,1,93.6,47.2,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,Goal,1,41,1,86.6,68.5,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,Goal,2,60,1,92.6,67.2,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,Goal,1,9,1,74.9,47.6,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,Goal,1,33,1,80.7,32.8,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

────────────────────────────────────────────────────────────
  qualifierId 395  |  598 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     598x   16 (Goal)

  Qualifier value distribution:
      22x   '99.1'
      21x   '98.6'
      21x   '1.0'
      19x   '98.5'
      18x   '1.4'
      17x   '1.1'
      17x   '98.4'
      17x   '1.2'
      16x   '0.6'
      16x   '98.9'

  Top co-occurring qualifiers:
     598x   qualifierId 396  (*** NOT IN MAPPING ***)
     598x   qualifierId 375  (*** NOT IN MAPPING ***)
     598x   qualifierId 374  (*** NOT IN MAPPING ***)
     598x   qualifierId 102  (Goal mouth y co-ordinate)
     598x   qualifierId 231  (GK Y Coordinate)
     598x   qualifierId 56  (Zone)
     598x   qualifierId 230  (GK X Coordinate)
     598x   qualifierId 103  (Goal mouth z co-ordinate)
     401x   qualifierId 29  (Assisted)
     401x   qualifierId 55  (Related event ID)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Goal,2,74,1,96.2,54.6,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,Goal,2,76,1,88.1,52.0,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,Goal,2,89,1,85.6,44.6,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,Goal,1,8,1,87.4,43.4,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,Goal,1,11,1,93.6,47.2,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,Goal,1,41,1,86.6,68.5,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,Goal,2,60,1,92.6,67.2,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,Goal,1,9,1,74.9,47.6,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,Goal,1,33,1,80.7,32.8,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

────────────────────────────────────────────────────────────
  qualifierId 396  |  598 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     598x   16 (Goal)

  Qualifier value distribution:
      19x   '51.3'
      18x   '51.8'
      17x   '52.3'
      17x   '49.8'
      16x   '48.2'
      16x   '51.6'
      16x   '47.5'
      15x   '47.8'
      15x   '52.2'
      14x   '52.7'

  Top co-occurring qualifiers:
     598x   qualifierId 395  (*** NOT IN MAPPING ***)
     598x   qualifierId 375  (*** NOT IN MAPPING ***)
     598x   qualifierId 374  (*** NOT IN MAPPING ***)
     598x   qualifierId 102  (Goal mouth y co-ordinate)
     598x   qualifierId 231  (GK Y Coordinate)
     598x   qualifierId 56  (Zone)
     598x   qualifierId 230  (GK X Coordinate)
     598x   qualifierId 103  (Goal mouth z co-ordinate)
     401x   qualifierId 29  (Assisted)
     401x   qualifierId 55  (Related event ID)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Goal,2,74,1,96.2,54.6,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,Goal,2,76,1,88.1,52.0,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,Goal,2,89,1,85.6,44.6,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,Goal,1,8,1,87.4,43.4,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,Goal,1,11,1,93.6,47.2,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,Goal,1,41,1,86.6,68.5,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,Goal,2,60,1,92.6,67.2,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,Goal,1,9,1,74.9,47.6,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,Goal,1,33,1,80.7,32.8,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

────────────────────────────────────────────────────────────
  qualifierId 391  |  255 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     233x   13 (Miss)
      22x   15 (Attempt Saved)

  Qualifier value distribution:
     255x   None

  Top co-occurring qualifiers:
     255x   qualifierId 103  (Goal mouth z co-ordinate)
     255x   qualifierId 56  (Zone)
     255x   qualifierId 102  (Goal mouth y co-ordinate)
     239x   qualifierId 230  (GK X Coordinate)
     239x   qualifierId 231  (GK Y Coordinate)
     214x   qualifierId 328  (First Time)
     184x   qualifierId 55  (Related event ID)
     184x   qualifierId 29  (Assisted)
     154x   qualifierId 22  (Regular play)
     154x   qualifierId 154  (Intentional assist)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,113wccwt50kebz0thqf0fxkpg,Miss,2,77,1,93.1,37.2,"[55, 29, 230, 75, 17, 22, 328, 103, 391, 20, 5..."
1,11hplskmrac4dwfmqv72f9nh0,Miss,1,22,1,89.2,36.8,"[102, 328, 29, 231, 108, 63, 103, 20, 22, 55, ..."
2,11uxeay5z2isuekqd9fq0usyc,Miss,2,64,1,82.8,61.7,"[215, 103, 230, 114, 24, 18, 153, 56, 391, 84,..."
3,12lophscpllg367yx7yn0mpec,Miss,1,1,1,85.9,51.5,"[17, 230, 147, 103, 146, 15, 153, 391, 231, 77..."
4,12lophscpllg367yx7yn0mpec,Miss,2,91,1,78.7,42.3,"[215, 230, 102, 103, 73, 153, 328, 18, 146, 14..."
5,13d50vdn5ecuddcpg1cvdrq50,Miss,1,36,1,89.9,55.9,"[20, 230, 56, 231, 22, 108, 103, 29, 17, 154, ..."
6,13qwzalezgy8gxih0ube0ap78,Miss,2,52,1,94.8,62.2,"[61, 147, 23, 72, 154, 56, 75, 55, 29, 103, 10..."
7,144g7b7ez101gt3yczm0yblzo,Miss,2,76,1,92.7,56.5,"[20, 17, 214, 102, 231, 114, 22, 103, 230, 391..."
8,15ir6pt6au1v00gtef02v4k,Miss,1,14,1,71.5,51.5,"[56, 153, 18, 55, 22, 231, 20, 103, 391, 146, ..."
9,15ojns8pjndvlncxp05js2cyc,Miss,1,7,1,89.0,54.0,"[154, 231, 391, 21, 102, 146, 56, 103, 328, 55..."

────────────────────────────────────────────────────────────
  qualifierId 468  |  243 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     104x   15 (Attempt Saved)
      73x   16 (Goal)
      63x   13 (Miss)
       3x   14 (Post)

  Qualifier value distribution:
       2x   '590'
       2x   '441'
       2x   '521'
       2x   '650'
       2x   '347'
       2x   '632'
       2x   '745'
       2x   '45'
       2x   '913'
       2x   '224'

  Top co-occurring qualifiers:
     243x   qualifierId 102  (Goal mouth y co-ordinate)
     243x   qualifierId 103  (Goal mouth z co-ordinate)
     243x   qualifierId 56  (Zone)
     206x   qualifierId 22  (Regular play)
     180x   qualifierId 230  (GK X Coordinate)
     180x   qualifierId 231  (GK Y Coordinate)
     137x   qualifierId 20  (Right footed)
     124x   qualifierId 55  (Related event ID)
     124x   qualifierId 29  (Assisted)
     119x   qualifierId 458  (*** NOT IN MAPPING ***)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Attempt Saved,2,92,1,96.8,69.5,"[20, 458, 147, 146, 22, 233, 102, 468, 103, 65..."
1,10qg7chtpoj0knqnvx2oduot0,Miss,1,3,1,96.4,62.2,"[56, 230, 231, 102, 468, 458, 61, 74, 328, 103..."
2,10qg7chtpoj0knqnvx2oduot0,Attempt Saved,1,28,1,87.7,41.9,"[55, 146, 468, 103, 102, 29, 56, 147, 154, 22,..."
3,113wccwt50kebz0thqf0fxkpg,Goal,1,8,1,87.4,43.4,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
4,113wccwt50kebz0thqf0fxkpg,Goal,1,11,1,93.6,47.2,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
5,113wccwt50kebz0thqf0fxkpg,Miss,2,77,1,86.7,46.8,"[230, 214, 72, 29, 102, 328, 56, 55, 154, 468,..."
6,11hplskmrac4dwfmqv72f9nh0,Attempt Saved,2,61,1,84.5,42.6,"[233, 154, 103, 328, 17, 22, 146, 102, 147, 78..."
7,11hplskmrac4dwfmqv72f9nh0,Attempt Saved,2,77,1,80.6,56.8,"[56, 233, 22, 146, 120, 102, 468, 55, 29, 79, ..."
8,11uxeay5z2isuekqd9fq0usyc,Miss,2,65,1,84.3,65.4,"[29, 64, 55, 102, 20, 231, 103, 22, 154, 56, 2..."
9,1288ajju0cadnuxxhvkal1mok,Attempt Saved,1,4,1,89.0,64.2,"[29, 468, 103, 233, 108, 64, 56, 154, 146, 147..."

────────────────────────────────────────────────────────────
  qualifierId 472  |  116 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
     116x   16 (Goal)

  Qualifier value distribution:
       2x   '749'
       2x   '475'
       2x   '482'
       2x   '741'
       1x   '664'
       1x   '584'
       1x   '148'
       1x   '1028'
       1x   '515'
       1x   '79'

  Top co-occurring qualifiers:
     116x   qualifierId 281  (Fantasy Assisted By)
     116x   qualifierId 375  (*** NOT IN MAPPING ***)
     116x   qualifierId 280  (Fantasy Assist Type)
     116x   qualifierId 374  (*** NOT IN MAPPING ***)
     116x   qualifierId 102  (Goal mouth y co-ordinate)
     116x   qualifierId 231  (GK Y Coordinate)
     116x   qualifierId 56  (Zone)
     116x   qualifierId 230  (GK X Coordinate)
     116x   qualifierId 103  (Goal mouth z co-ordinate)
     116x   qualifierId 282  (Fantasy Assist Team)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Goal,2,74,1,96.2,54.6,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,1288ajju0cadnuxxhvkal1mok,Goal,1,18,1,88.5,50.0,"[472, 9, 230, 458, 375, 20, 353, 281, 395, 76,..."
3,1288ajju0cadnuxxhvkal1mok,Goal,2,81,1,89.0,75.2,"[282, 22, 458, 230, 81, 72, 472, 215, 64, 281,..."
4,12zi2fz6nuyhye00alaymbms4,Goal,2,65,1,88.6,58.1,"[280, 328, 20, 231, 25, 374, 108, 78, 472, 103..."
5,144g7b7ez101gt3yczm0yblzo,Goal,1,4,1,85.9,49.2,"[20, 282, 280, 231, 375, 17, 396, 214, 76, 102..."
6,14xa2ysiarbslbwcla4hhzqj8,Goal,2,79,1,96.7,51.3,"[282, 396, 78, 458, 56, 72, 214, 468, 280, 375..."
7,15au35re7u5b9ru4hoko7f3f8,Goal,2,88,1,88.5,50.0,"[17, 102, 214, 231, 56, 472, 72, 374, 353, 395..."
8,15ir6pt6au1v00gtef02v4k,Goal,2,67,1,94.9,44.0,"[282, 375, 458, 20, 214, 231, 472, 396, 56, 78..."
9,15ir6pt6au1v00gtef02v4k,Goal,2,91,1,97.1,58.9,"[282, 231, 374, 24, 472, 214, 56, 77, 396, 230..."

────────────────────────────────────────────────────────────
  qualifierId 390  |  85 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
      66x   16 (Goal)
      13x   15 (Attempt Saved)
       3x   14 (Post)
       3x   13 (Miss)

  Qualifier value distribution:
       2x   '82263'
       2x   '498444'
       2x   '494928'
       2x   '58877'
       2x   '210171'
       2x   '170116'
       2x   '42670'
       2x   '539600'
       2x   '500759'
       2x   '105571'

  Top co-occurring qualifiers:
      85x   qualifierId 458  (*** NOT IN MAPPING ***)
      85x   qualifierId 17  (Box-centre)
      85x   qualifierId 214  (Big Chance)
      85x   qualifierId 353  (*** NOT IN MAPPING ***)
      85x   qualifierId 102  (Goal mouth y co-ordinate)
      85x   qualifierId 103  (Goal mouth z co-ordinate)
      85x   qualifierId 56  (Zone)
      85x   qualifierId 9  (Penalty)
      72x   qualifierId 231  (GK Y Coordinate)
      72x   qualifierId 230  (GK X Coordinate)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
1,11uxeay5z2isuekqd9fq0usyc,Goal,2,93,1,88.5,50.0,"[395, 102, 353, 214, 375, 56, 231, 374, 20, 23..."
2,1288ajju0cadnuxxhvkal1mok,Goal,1,18,1,88.5,50.0,"[472, 9, 230, 458, 375, 20, 353, 281, 395, 76,..."
3,1288ajju0cadnuxxhvkal1mok,Attempt Saved,1,42,1,88.5,50.0,"[9, 233, 146, 20, 353, 102, 17, 56, 390, 458, ..."
4,12zi2fz6nuyhye00alaymbms4,Post,1,36,1,88.5,50.0,"[390, 103, 20, 102, 56, 230, 9, 17, 458, 214, ..."
5,15au35re7u5b9ru4hoko7f3f8,Goal,2,88,1,88.5,50.0,"[17, 102, 214, 231, 56, 472, 72, 374, 353, 395..."
6,16t0fdut4ky4b4es7i0trovtg,Goal,1,9,1,88.5,50.0,"[102, 20, 375, 214, 9, 395, 390, 280, 80, 17, ..."
7,17xoblao6gdkidisaddnrpa1g,Goal,2,50,1,88.5,50.0,"[374, 231, 280, 282, 281, 102, 214, 20, 230, 3..."
8,19ubgm1lxlw64hrajkv1cc5ck,Attempt Saved,2,66,1,88.5,50.0,"[72, 103, 78, 147, 17, 146, 102, 353, 458, 214..."
9,1bpdzkqykdmb75z4uarby311w,Goal,2,54,1,88.5,50.0,"[230, 9, 458, 375, 76, 56, 396, 17, 72, 390, 2..."

────────────────────────────────────────────────────────────
  qualifierId 353  |  85 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
      66x   16 (Goal)
      13x   15 (Attempt Saved)
       3x   14 (Post)
       3x   13 (Miss)

  Qualifier value distribution:
       2x   '286'
       2x   '636'
       1x   '667'
       1x   '709'
       1x   '132'
       1x   '790'
       1x   '933'
       1x   '56'
       1x   '371'
       1x   '712'

  Top co-occurring qualifiers:
      85x   qualifierId 458  (*** NOT IN MAPPING ***)
      85x   qualifierId 17  (Box-centre)
      85x   qualifierId 214  (Big Chance)
      85x   qualifierId 390  (*** NOT IN MAPPING ***)
      85x   qualifierId 102  (Goal mouth y co-ordinate)
      85x   qualifierId 103  (Goal mouth z co-ordinate)
      85x   qualifierId 56  (Zone)
      85x   qualifierId 9  (Penalty)
      72x   qualifierId 231  (GK Y Coordinate)
      72x   qualifierId 230  (GK X Coordinate)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
1,11uxeay5z2isuekqd9fq0usyc,Goal,2,93,1,88.5,50.0,"[395, 102, 353, 214, 375, 56, 231, 374, 20, 23..."
2,1288ajju0cadnuxxhvkal1mok,Goal,1,18,1,88.5,50.0,"[472, 9, 230, 458, 375, 20, 353, 281, 395, 76,..."
3,1288ajju0cadnuxxhvkal1mok,Attempt Saved,1,42,1,88.5,50.0,"[9, 233, 146, 20, 353, 102, 17, 56, 390, 458, ..."
4,12zi2fz6nuyhye00alaymbms4,Post,1,36,1,88.5,50.0,"[390, 103, 20, 102, 56, 230, 9, 17, 458, 214, ..."
5,15au35re7u5b9ru4hoko7f3f8,Goal,2,88,1,88.5,50.0,"[17, 102, 214, 231, 56, 472, 72, 374, 353, 395..."
6,16t0fdut4ky4b4es7i0trovtg,Goal,1,9,1,88.5,50.0,"[102, 20, 375, 214, 9, 395, 390, 280, 80, 17, ..."
7,17xoblao6gdkidisaddnrpa1g,Goal,2,50,1,88.5,50.0,"[374, 231, 280, 282, 281, 102, 214, 20, 230, 3..."
8,19ubgm1lxlw64hrajkv1cc5ck,Attempt Saved,2,66,1,88.5,50.0,"[72, 103, 78, 147, 17, 146, 102, 353, 458, 214..."
9,1bpdzkqykdmb75z4uarby311w,Goal,2,54,1,88.5,50.0,"[230, 9, 458, 375, 76, 56, 396, 17, 72, 390, 2..."

────────────────────────────────────────────────────────────
  qualifierId 300  |  28 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
      28x   16 (Goal)

  Qualifier value distribution:
      28x   None

  Top co-occurring qualifiers:
      28x   qualifierId 102  (Goal mouth y co-ordinate)
      28x   qualifierId 374  (*** NOT IN MAPPING ***)
      28x   qualifierId 231  (GK Y Coordinate)
      28x   qualifierId 375  (*** NOT IN MAPPING ***)
      28x   qualifierId 230  (GK X Coordinate)
      28x   qualifierId 56  (Zone)
      28x   qualifierId 103  (Goal mouth z co-ordinate)
      27x   qualifierId 396  (*** NOT IN MAPPING ***)
      27x   qualifierId 395  (*** NOT IN MAPPING ***)
      27x   qualifierId 215  (Individual Play)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1288ajju0cadnuxxhvkal1mok,Goal,1,43,1,81.1,68.9,"[102, 374, 22, 231, 18, 396, 120, 20, 254, 55,..."
1,13qwzalezgy8gxih0ube0ap78,Goal,1,21,1,89.2,33.6,"[22, 395, 56, 254, 29, 230, 55, 20, 375, 274, ..."
2,13qwzalezgy8gxih0ube0ap78,Goal,2,55,1,76.0,54.6,"[80, 231, 18, 300, 215, 56, 230, 29, 102, 55, ..."
3,14ia91hr21lnjto1f2uga5f6c,Goal,1,24,1,94.8,65.2,"[396, 29, 374, 300, 102, 138, 103, 79, 214, 72..."
4,18ojlro5jtdeu8nv72repur6c,Goal,2,83,1,81.6,53.4,"[55, 102, 29, 76, 375, 231, 230, 103, 136, 56,..."
5,1eaz7mdny12eiuyeysnycnw2c,Goal,2,53,1,87.0,51.9,"[20, 103, 231, 396, 395, 22, 230, 102, 254, 17..."
6,1hbkc2pl94wmoej46f3izy4gk,Goal,1,49,1,82.8,29.9,"[375, 230, 72, 77, 102, 29, 374, 22, 215, 396,..."
7,1lud5oppwm3ngiyzarvb1zoyc,Goal,2,88,1,92.5,56.5,"[17, 136, 375, 138, 22, 273, 215, 20, 56, 374,..."
8,1m7vig0k2tt5q9apse7108pas,Goal,1,23,1,84.6,55.8,"[375, 396, 81, 120, 55, 231, 29, 300, 20, 395,..."
9,1qdreckuiubqc7yotymp8jggk,Goal,1,5,1,87.0,39.7,"[254, 22, 374, 102, 56, 113, 396, 29, 300, 214..."

────────────────────────────────────────────────────────────
  qualifierId 362  |  21 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
      14x   16 (Goal)
       4x   13 (Miss)
       2x   15 (Attempt Saved)
       1x   14 (Post)

  Qualifier value distribution:
      20x   '1'
       1x   '2'

  Top co-occurring qualifiers:
      21x   qualifierId 56  (Zone)
      21x   qualifierId 103  (Goal mouth z co-ordinate)
      21x   qualifierId 102  (Goal mouth y co-ordinate)
      19x   qualifierId 231  (GK Y Coordinate)
      19x   qualifierId 230  (GK X Coordinate)
      18x   qualifierId 55  (Related event ID)
      18x   qualifierId 29  (Assisted)
      14x   qualifierId 154  (Intentional assist)
      14x   qualifierId 215  (Individual Play)
      14x   qualifierId 20  (Right footed)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1uwb3z5cnpg9o84qdcr5r2o7o,Attempt Saved,1,0,1,87.4,47.4,"[154, 215, 56, 233, 328, 17, 23, 55, 20, 108, ..."
1,1v9qqviahmnia4ewmzd4aejv8,Miss,1,35,1,88.5,50.0,"[458, 214, 231, 77, 20, 390, 102, 353, 230, 17..."
2,1wwdsnnj2m9ewz1d1mgt7y8k,Post,2,56,1,91.2,47.2,"[73, 231, 102, 214, 20, 55, 103, 230, 29, 154,..."
3,1ydvgoo74zv2bvij485wtc93o,Goal,1,43,1,95.7,55.0,"[395, 103, 396, 214, 16, 22, 362, 231, 375, 55..."
4,22jwwfu5djp7vwtjkvcujieqc,Goal,2,91,1,89.8,54.4,"[108, 396, 374, 29, 22, 103, 17, 216, 102, 154..."
5,2au8colu3pbwws92o9q03i9zo,Goal,1,34,1,93.3,52.0,"[22, 154, 375, 102, 17, 362, 29, 108, 328, 20,..."
6,2cp6ugeg62t6fg02bkkkukums,Goal,2,80,1,85.5,50.8,"[396, 215, 362, 375, 103, 56, 230, 136, 20, 32..."
7,8o8bord6whrdh4yaej7v766s,Miss,2,91,1,96.7,53.3,"[56, 16, 20, 29, 391, 75, 328, 22, 231, 214, 2..."
8,exqzwxpls360bd9qf89ggff8,Miss,2,94,1,95.4,44.0,"[231, 214, 29, 56, 102, 362, 103, 154, 60, 55,..."
9,fo7f0yq3c06q4hrw7vamnnro,Goal,2,69,1,94.5,48.1,"[103, 395, 214, 22, 396, 55, 102, 375, 374, 36..."

────────────────────────────────────────────────────────────
  qualifierId 343  |  16 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       9x   16 (Goal)
       7x   15 (Attempt Saved)

  Qualifier value distribution:
      11x   '3'
       5x   '2'

  Top co-occurring qualifiers:
      16x   qualifierId 56  (Zone)
      16x   qualifierId 102  (Goal mouth y co-ordinate)
      16x   qualifierId 103  (Goal mouth z co-ordinate)
      15x   qualifierId 230  (GK X Coordinate)
      15x   qualifierId 231  (GK Y Coordinate)
      12x   qualifierId 20  (Right footed)
      11x   qualifierId 29  (Assisted)
      11x   qualifierId 55  (Related event ID)
      10x   qualifierId 17  (Box-centre)
       9x   qualifierId 22  (Regular play)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1288ajju0cadnuxxhvkal1mok,Attempt Saved,1,14,1,92.4,57.0,"[15, 29, 56, 154, 147, 25, 78, 82, 17, 55, 328..."
1,16t0fdut4ky4b4es7i0trovtg,Attempt Saved,1,6,1,79.7,38.5,"[343, 231, 82, 22, 76, 56, 230, 215, 146, 103,..."
2,1a7radhhole7vfnciarzauq6s,Goal,2,89,1,84.7,50.7,"[29, 374, 56, 20, 80, 17, 55, 396, 395, 375, 2..."
3,1bbwtdnimi7tbl6aatezlnwno,Goal,2,82,1,98.9,45.8,"[214, 395, 230, 56, 22, 103, 102, 80, 282, 72,..."
4,1cg5aiu7phyw89gyr0m9hme50,Goal,2,91,1,91.8,48.1,"[374, 108, 20, 102, 230, 154, 160, 55, 80, 343..."
5,1gkqfp2d7qi9h6k34k3mo8zkk,Attempt Saved,2,53,1,85.6,65.7,"[215, 231, 78, 55, 82, 103, 102, 192, 343, 20,..."
6,1v9qqviahmnia4ewmzd4aejv8,Goal,1,18,1,88.3,57.0,"[215, 214, 17, 103, 396, 23, 20, 343, 56, 78, ..."
7,24ggs30od6yf2dz3uyz8zjlec,Attempt Saved,2,69,1,76.4,63.9,"[79, 56, 22, 215, 29, 103, 18, 147, 55, 343, 2..."
8,5pp18hcr9ery2hv17q7q6eqc,Attempt Saved,1,48,1,87.2,62.0,"[230, 146, 82, 103, 23, 233, 147, 102, 20, 192..."
9,6g1tozuo8an9qds56u85juhg,Goal,1,45,1,88.5,50.0,"[390, 20, 230, 280, 458, 231, 17, 375, 281, 39..."

────────────────────────────────────────────────────────────
  qualifierId 314  |  11 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       8x   13 (Miss)
       3x   15 (Attempt Saved)

  Qualifier value distribution:
      11x   None

  Top co-occurring qualifiers:
      11x   qualifierId 102  (Goal mouth y co-ordinate)
      11x   qualifierId 230  (GK X Coordinate)
      11x   qualifierId 147  (Blocked y co-ordinate)
      11x   qualifierId 231  (GK Y Coordinate)
      11x   qualifierId 56  (Zone)
      11x   qualifierId 103  (Goal mouth z co-ordinate)
      11x   qualifierId 146  (Blocked x co-ordinate)
       9x   qualifierId 328  (First Time)
       8x   qualifierId 153  (Not past goal line)
       8x   qualifierId 17  (Box-centre)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1dk2hnl09qux7z4fqn1qxq238,Miss,1,24,1,77.1,58.5,"[314, 102, 230, 147, 391, 153, 328, 18, 108, 7..."
1,1dk2hnl09qux7z4fqn1qxq238,Miss,2,77,1,90.2,51.0,"[230, 154, 153, 103, 328, 391, 56, 20, 55, 147..."
2,1l3ezfcz5pfa7eixz6hnfmj9w,Miss,1,15,1,92.5,52.9,"[29, 328, 314, 102, 56, 147, 154, 103, 84, 17,..."
3,1ydvgoo74zv2bvij485wtc93o,Attempt Saved,1,23,1,80.6,63.4,"[147, 56, 22, 230, 78, 146, 231, 72, 18, 82, 1..."
4,23c7lgceh27fdelyfo5a4ygwk,Miss,1,1,1,90.9,60.7,"[102, 153, 73, 22, 56, 147, 314, 230, 154, 29,..."
5,257ci0bd6g6l3uk1fn5a0ob2s,Miss,2,74,1,90.5,43.6,"[56, 314, 102, 231, 153, 17, 75, 147, 103, 458..."
6,28z661pl07w40fr1in36f97o4,Attempt Saved,2,76,1,85.5,55.2,"[230, 139, 103, 147, 82, 102, 146, 458, 231, 3..."
7,av0qyy8sbq3jo28muv6smb6c,Attempt Saved,2,65,1,83.0,32.9,"[108, 55, 146, 231, 18, 328, 154, 20, 147, 139..."
8,kxz64yu7ddap0d1agwdxugwk,Miss,2,88,1,85.0,53.2,"[72, 146, 230, 231, 160, 56, 17, 147, 55, 102,..."
9,s2odkp4oybdaqou9lx1fd6ok,Miss,2,53,1,94.0,47.9,"[102, 55, 29, 153, 154, 328, 17, 314, 231, 56,..."

────────────────────────────────────────────────────────────
  qualifierId 487  |  3 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       2x   16 (Goal)
       1x   14 (Post)

  Qualifier value distribution:
       3x   None

  Top co-occurring qualifiers:
       3x   qualifierId 9  (Penalty)
       3x   qualifierId 102  (Goal mouth y co-ordinate)
       3x   qualifierId 231  (GK Y Coordinate)
       3x   qualifierId 114  (Weak)
       3x   qualifierId 353  (*** NOT IN MAPPING ***)
       3x   qualifierId 214  (Big Chance)
       3x   qualifierId 56  (Zone)
       3x   qualifierId 390  (*** NOT IN MAPPING ***)
       3x   qualifierId 458  (*** NOT IN MAPPING ***)
       3x   qualifierId 17  (Box-centre)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,242xbwdul3xv3pwz602l6btw4,Goal,2,93,1,88.5,50.0,"[375, 9, 374, 102, 231, 114, 353, 487, 214, 56..."
1,jfjnqx2yal5t4pcccve1zg9g,Goal,2,63,1,88.5,50.0,"[114, 231, 458, 353, 374, 396, 17, 102, 20, 10..."
2,z7hbnyt9xc1j8x9pacy6jmdw,Post,2,78,1,88.5,50.0,"[74, 214, 231, 458, 353, 230, 102, 56, 487, 9,..."

────────────────────────────────────────────────────────────
  qualifierId 358  |  1 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       1x   16 (Goal)

  Qualifier value distribution:
       1x   None

  Top co-occurring qualifiers:
       1x   qualifierId 374  (*** NOT IN MAPPING ***)
       1x   qualifierId 231  (GK Y Coordinate)
       1x   qualifierId 396  (*** NOT IN MAPPING ***)
       1x   qualifierId 56  (Zone)
       1x   qualifierId 102  (Goal mouth y co-ordinate)
       1x   qualifierId 103  (Goal mouth z co-ordinate)
       1x   qualifierId 76  (Low left)
       1x   qualifierId 29  (Assisted)
       1x   qualifierId 230  (GK X Coordinate)
       1x   qualifierId 375  (*** NOT IN MAPPING ***)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1o35rsofsxiepozlbmke0wduc,Goal,1,37,1,84.8,62.3,"[374, 231, 396, 56, 102, 103, 76, 29, 230, 375..."

────────────────────────────────────────────────────────────
  qualifierId 484  |  1 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       1x   16 (Goal)

  Qualifier value distribution:
       1x   None

  Top co-occurring qualifiers:
       1x   qualifierId 374  (*** NOT IN MAPPING ***)
       1x   qualifierId 231  (GK Y Coordinate)
       1x   qualifierId 396  (*** NOT IN MAPPING ***)
       1x   qualifierId 56  (Zone)
       1x   qualifierId 102  (Goal mouth y co-ordinate)
       1x   qualifierId 103  (Goal mouth z co-ordinate)
       1x   qualifierId 76  (Low left)
       1x   qualifierId 29  (Assisted)
       1x   qualifierId 230  (GK X Coordinate)
       1x   qualifierId 375  (*** NOT IN MAPPING ***)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1o35rsofsxiepozlbmke0wduc,Goal,1,37,1,84.8,62.3,"[374, 231, 396, 56, 102, 103, 76, 29, 230, 375..."

────────────────────────────────────────────────────────────
  qualifierId 459  |  1 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       1x   15 (Attempt Saved)

  Qualifier value distribution:
       1x   None

  Top co-occurring qualifiers:
       1x   qualifierId 146  (Blocked x co-ordinate)
       1x   qualifierId 147  (Blocked y co-ordinate)
       1x   qualifierId 233  (Opposite related event ID)
       1x   qualifierId 76  (Low left)
       1x   qualifierId 29  (Assisted)
       1x   qualifierId 215  (Individual Play)
       1x   qualifierId 24  (Set piece)
       1x   qualifierId 103  (Goal mouth z co-ordinate)
       1x   qualifierId 490  (*** NOT IN MAPPING ***)
       1x   qualifierId 20  (Right footed)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1xweeu166hhelv9hh9l8lnpjo,Attempt Saved,1,46,1,73.4,35.8,"[146, 147, 459, 233, 76, 29, 215, 24, 103, 490..."

────────────────────────────────────────────────────────────
  qualifierId 490  |  1 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       1x   15 (Attempt Saved)

  Qualifier value distribution:
       1x   '17'

  Top co-occurring qualifiers:
       1x   qualifierId 146  (Blocked x co-ordinate)
       1x   qualifierId 147  (Blocked y co-ordinate)
       1x   qualifierId 459  (*** NOT IN MAPPING ***)
       1x   qualifierId 233  (Opposite related event ID)
       1x   qualifierId 76  (Low left)
       1x   qualifierId 29  (Assisted)
       1x   qualifierId 215  (Individual Play)
       1x   qualifierId 24  (Set piece)
       1x   qualifierId 103  (Goal mouth z co-ordinate)
       1x   qualifierId 20  (Right footed)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1xweeu166hhelv9hh9l8lnpjo,Attempt Saved,1,46,1,73.4,35.8,"[146, 147, 459, 233, 76, 29, 215, 24, 103, 490..."

────────────────────────────────────────────────────────────
  qualifierId 474  |  1 occurrences on shots
────────────────────────────────────────────────────────────

  Shot types that carry this qualifier:
       1x   13 (Miss)

  Qualifier value distribution:
       1x   '465'

  Top co-occurring qualifiers:
       1x   qualifierId 102  (Goal mouth y co-ordinate)
       1x   qualifierId 17  (Box-centre)
       1x   qualifierId 231  (GK Y Coordinate)
       1x   qualifierId 56  (Zone)
       1x   qualifierId 22  (Regular play)
       1x   qualifierId 55  (Related event ID)
       1x   qualifierId 121  (Swerve Right)
       1x   qualifierId 73  (Left)
       1x   qualifierId 72  (Left footed)
       1x   qualifierId 468  (*** NOT IN MAPPING ***)

  Sample shots (up to 10):

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,1z79bgsg0g4xojqjpoxolh1ck,Miss,2,54,1,87.7,38.9,"[102, 17, 231, 56, 22, 55, 121, 73, 72, 468, 2..."

In [6]:
# ── Per-shot-type qualifier breakdown ─────────────────────────────────────────
# For each shot typeId, show how often each qualifier appears (as % of that shot type).
# This makes it easy to spot qualifiers that cluster on only one type.

for tid, name in SHOT_TYPE_NAMES.items():
    subset = [s for s in shots if s["type_id"] == tid]
    if not subset:
        continue

    n = len(subset)
    qual_counts: Counter = Counter()
    for s in subset:
        qual_counts.update(s["qualifier_ids"])

    print("=" * 60)
    print(f"  typeId {tid} — {name}   ({n:,} events)")
    print("=" * 60)

    rows = []
    for qid, cnt in qual_counts.most_common():
        rows.append({
            "qualifierId": qid,
            "name"       : qual_name(qid, quals_mapping),
            "count"      : cnt,
            "pct"        : f"{cnt / n * 100:.1f}%",
            "in_mapping" : qid in quals_mapping,
        })
    display(pd.DataFrame(rows))
    print()

============================================================
  typeId 13 — Miss   (2,163 events)
============================================================

    qualifierId                       name  count     pct  in_mapping
0           103   Goal mouth z co-ordinate   2163  100.0%        True
1           231            GK Y Coordinate   2163  100.0%        True
2           102   Goal mouth y co-ordinate   2163  100.0%        True
3           230            GK X Coordinate   2163  100.0%        True
4            56                       Zone   2163  100.0%        True
..          ...                        ...    ...     ...         ...
65           71                   35+ left      2    0.1%        True
66          233  Opposite related event ID      1    0.0%        True
67           70                  35+ right      1    0.0%        True
68          474     *** NOT IN MAPPING ***      1    0.0%       False
69          133                 Deflection      1    0.0%        True

[70 rows x 5 columns]

============================================================
  typeId 14 — Post   (98 events)
============================================================

    qualifierId                      name  count     pct  in_mapping
0           102  Goal mouth y co-ordinate     98  100.0%        True
1           231           GK Y Coordinate     98  100.0%        True
2            56                      Zone     98  100.0%        True
3           230           GK X Coordinate     98  100.0%        True
4           103  Goal mouth z co-ordinate     98  100.0%        True
5            55          Related event ID     70   71.4%        True
6            29                  Assisted     70   71.4%        True
7            22              Regular play     56   57.1%        True
8            20              Right footed     52   53.1%        True
9           328                First Time     47   48.0%        True
10          154        Intentional assist     44   44.9%        True
11           74                      High     44   44.9%        True
12           17                Box-centre     34   34.7%        True
13          214                Big Chance     34   34.7%        True
14           72               Left footed     32   32.7%        True
15          215           Individual Play     31   31.6%        True
16           75                     Right     29   29.6%        True
17           18         Out of box-centre     29   29.6%        True
18          458    *** NOT IN MAPPING ***     28   28.6%       False
19           73                      Left     25   25.5%        True
20           25               From corner     16   16.3%        True
21           15                      Head     13   13.3%        True
22          120               Swerve Left     12   12.2%        True
23           64                  Box-left     11   11.2%        True
24          121              Swerve Right     11   11.2%        True
25           23                Fast break     10   10.2%        True
26          108                    Volley      8    8.2%        True
27           26                 Free kick      6    6.1%        True
28           63                 Box-right      5    5.1%        True
29           89                    1 on 1      5    5.1%        True
30           60           Small box-right      5    5.1%        True
31           61            Small box-left      5    5.1%        True
32           24                 Set piece      4    4.1%        True
33           16          Small box-centre      4    4.1%        True
34          390    *** NOT IN MAPPING ***      3    3.1%       False
35            9                   Penalty      3    3.1%        True
36          353    *** NOT IN MAPPING ***      3    3.1%       False
37          468    *** NOT IN MAPPING ***      3    3.1%       False
38          122             Swerve Moving      3    3.1%        True
39          160        Throw-in set piece      3    3.1%        True
40          113                    Strong      3    3.1%        True
41          114                      Weak      2    2.0%        True
42           66     Out of box-deep right      2    2.0%        True
43           19                35+ centre      1    1.0%        True
44          362    *** NOT IN MAPPING ***      1    1.0%       False
45           21           Other body part      1    1.0%        True
46           62            Box-deep right      1    1.0%        True
47           65             Box-deep left      1    1.0%        True
48          487    *** NOT IN MAPPING ***      1    1.0%       False

============================================================
  typeId 15 — Attempt Saved   (2,927 events)
============================================================

    qualifierId                      name  count     pct  in_mapping
0           102  Goal mouth y co-ordinate   2927  100.0%        True
1           103  Goal mouth z co-ordinate   2927  100.0%        True
2           146     Blocked x co-ordinate   2927  100.0%        True
3           147     Blocked y co-ordinate   2927  100.0%        True
4            56                      Zone   2927  100.0%        True
..          ...                       ...    ...     ...         ...
67           66     Out of box-deep right      2    0.1%        True
68          362    *** NOT IN MAPPING ***      2    0.1%       False
69           21           Other body part      2    0.1%        True
70          459    *** NOT IN MAPPING ***      1    0.0%       False
71          490    *** NOT IN MAPPING ***      1    0.0%       False

[72 rows x 5 columns]

============================================================
  typeId 16 — Goal   (605 events)
============================================================

    qualifierId                      name  count     pct  in_mapping
0           375    *** NOT IN MAPPING ***    605  100.0%       False
1           374    *** NOT IN MAPPING ***    605  100.0%       False
2           102  Goal mouth y co-ordinate    605  100.0%        True
3           231           GK Y Coordinate    605  100.0%        True
4            56                      Zone    605  100.0%        True
..          ...                       ...    ...     ...         ...
69          487    *** NOT IN MAPPING ***      2    0.3%       False
70          358    *** NOT IN MAPPING ***      1    0.2%       False
71          484    *** NOT IN MAPPING ***      1    0.2%       False
72          122             Swerve Moving      1    0.2%        True
73           68           Out of box-left      1    0.2%        True

[74 rows x 5 columns]

In [7]:
# ── Summary card ──────────────────────────────────────────────────────────────

all_qids_on_shots  = set(all_qual_counts.keys())
qids_in_mapping    = set(quals_mapping.keys())
unknown_qids       = all_qids_on_shots - qids_in_mapping
covered_qids       = all_qids_on_shots & qids_in_mapping

print("=" * 55)
print(" SHOT QUALIFIER AUDIT SUMMARY")
print("=" * 55)
print(f"  Shot events scanned          : {total_shots:,}")
print(f"  Distinct qualifier IDs seen  : {len(all_qids_on_shots)}")
print(f"  Covered by opta-qualifiers   : {len(covered_qids)}")
print(f"  ⚠  NOT in mapping (unknown) : {len(unknown_qids)}", end="")
print("  ← investigate!" if unknown_qids else "")
print("=" * 55)

if unknown_qids:
    print(f"\n⚠  Unknown qualifier IDs on shots: {sorted(unknown_qids)}")
    print("   See cell 5 above for full breakdown.")
else:
    print("\n✅  All qualifiers on shots are documented in opta-qualifiers.js.")

=======================================================
 SHOT QUALIFIER AUDIT SUMMARY
=======================================================
  Shot events scanned          : 5,793
  Distinct qualifier IDs seen  : 103
  Covered by opta-qualifiers   : 83
  ⚠  NOT in mapping (unknown) : 20  ← investigate!
=======================================================

⚠  Unknown qualifier IDs on shots: [300, 314, 343, 353, 358, 362, 374, 375, 390, 391, 395, 396, 458, 459, 468, 472, 474, 484, 487, 490]
   See cell 5 above for full breakdown.

In [8]:
# ── Video verification samples: qualifiers 328 and 428 on goals ──────────────
# For each qualifier: 10 goals WITH it, 10 goals WITHOUT it.
# Columns: source_match_id, period, minute, second — enough to locate the clip.

##TARGET_QUALIFIERS = [328, 458]
TARGET_QUALIFIERS = [24,25,26,96]
N_SAMPLES         = 10


def scan_goals_for_video(matches_dir: Path) -> list[dict]:
    """Re-scan all files for goals (typeId 16), pulling source_match_id and timeSec."""
    goals = []
    for fp in sorted(p for p in matches_dir.iterdir() if p.is_file() and not p.name.startswith(".")):
        try:
            data = extract_json_from_jsonp(fp)
        except Exception:
            continue
        source_match_id = data.get("matchInfo", {}).get("id", fp.name)
        for ev in data["liveData"]["event"]:
            if ev.get("typeId") != 16:
                continue
            qualifier_ids = [q.get("qualifierId") for q in ev.get("qualifier", [])]
            goals.append({
                "source_match_id": source_match_id,
                "period"         : ev.get("periodId"),
                "minute"         : ev.get("timeMin"),
                "second"         : ev.get("timeSec"),
                "qualifier_ids"  : qualifier_ids,
            })
    return goals


def show_goals(rows: list[dict], label: str) -> None:
    if not rows:
        print(f"  (no goals found for: {label})")
        return
    display(pd.DataFrame(rows)[["source_match_id", "period", "minute", "second", "qualifier_ids"]])


goals = scan_goals_for_video(MATCHES_DIR)
print(f"Total goals collected: {len(goals):,}\n")

for qid in TARGET_QUALIFIERS:
    with_q    = [g for g in goals if     qid in g["qualifier_ids"]][:N_SAMPLES]
    without_q = [g for g in goals if qid not in g["qualifier_ids"]][:N_SAMPLES]

    print("=" * 65)
    print(f"  qualifierId {qid}   —   {qual_name(qid, quals_mapping)}")
    print(f"  Goals WITH: {sum(1 for g in goals if qid in g['qualifier_ids'])}   |   "
          f"Goals WITHOUT: {sum(1 for g in goals if qid not in g['qualifier_ids'])}")
    print("=" * 65)

    print(f"\n  ✅  {N_SAMPLES} goals WITH qualifierId {qid}:")
    show_goals(with_q, f"WITH {qid}")

    print(f"\n  ❌  {N_SAMPLES} goals WITHOUT qualifierId {qid}:")
    show_goals(without_q, f"WITHOUT {qid}")
    print()

Total goals collected: 605

=================================================================
  qualifierId 24   —   Set piece
  Goals WITH: 28   |   Goals WITHOUT: 577
=================================================================

  ✅  10 goals WITH qualifierId 24:

,source_match_id,period,minute,second,qualifier_ids
0,11uxeay5z2isuekqd9fq0usyc,2,71,28,"[15, 17, 231, 328, 55, 154, 396, 29, 102, 230,..."
1,12lophscpllg367yx7yn0mpec,1,41,40,"[17, 103, 328, 78, 396, 55, 24, 395, 231, 374,..."
2,12lophscpllg367yx7yn0mpec,2,78,40,"[375, 103, 102, 458, 136, 16, 56, 395, 396, 23..."
3,15ir6pt6au1v00gtef02v4k,2,91,6,"[282, 231, 374, 24, 472, 214, 56, 77, 396, 230..."
4,18ojlro5jtdeu8nv72repur6c,2,86,25,"[395, 20, 16, 374, 24, 55, 214, 56, 375, 103, ..."
5,1eaz7mdny12eiuyeysnycnw2c,2,67,57,"[472, 396, 230, 281, 113, 458, 231, 77, 280, 2..."
6,1nc8632r4hii9bl1ygnappkpg,1,37,49,"[29, 230, 154, 102, 375, 328, 231, 24, 77, 103..."
7,1p93rklxg8b0b4dymsqjlcbh0,1,22,5,"[154, 29, 76, 72, 55, 231, 374, 396, 17, 375, ..."
8,1pmmfccm8cfhw6hua3w0gz28k,1,43,48,"[374, 108, 215, 396, 72, 458, 102, 395, 230, 1..."
9,1q09wu5t41r3rdtsv757pyf4k,2,59,19,"[230, 56, 374, 24, 55, 103, 29, 395, 396, 231,..."

  ❌  10 goals WITHOUT qualifierId 24:

,source_match_id,period,minute,second,qualifier_ids
0,10d1132abu0fa9xolj05top3o,2,74,13,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,2,63,52,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,2,76,31,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,2,89,9,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,1,8,28,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,1,11,0,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,1,41,28,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,2,60,3,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,1,9,39,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,1,33,41,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

=================================================================
  qualifierId 25   —   From corner
  Goals WITH: 70   |   Goals WITHOUT: 535
=================================================================

  ✅  10 goals WITH qualifierId 25:

,source_match_id,period,minute,second,qualifier_ids
0,11uxeay5z2isuekqd9fq0usyc,2,85,43,"[154, 396, 214, 72, 25, 79, 395, 374, 375, 60,..."
1,12lophscpllg367yx7yn0mpec,2,91,48,"[17, 56, 55, 214, 103, 102, 375, 113, 230, 396..."
2,12zi2fz6nuyhye00alaymbms4,1,39,20,"[102, 395, 374, 29, 81, 396, 55, 136, 375, 120..."
3,12zi2fz6nuyhye00alaymbms4,2,65,8,"[280, 328, 20, 231, 25, 374, 108, 78, 472, 103..."
4,14xa2ysiarbslbwcla4hhzqj8,1,20,35,"[374, 396, 15, 375, 77, 328, 102, 154, 214, 13..."
5,15ir6pt6au1v00gtef02v4k,1,35,56,"[214, 375, 29, 374, 328, 25, 396, 230, 56, 103..."
6,16t0fdut4ky4b4es7i0trovtg,2,72,51,"[231, 29, 17, 375, 396, 80, 154, 273, 395, 102..."
7,176p8ms7mmtnsyiwqb87aavx0,2,81,38,"[458, 25, 396, 375, 17, 102, 72, 395, 121, 230..."
8,18b3vyjp3y356x49ce7z1qdxw,2,74,36,"[231, 25, 103, 395, 396, 375, 56, 328, 374, 29..."
9,18ojlro5jtdeu8nv72repur6c,2,77,22,"[29, 230, 231, 396, 328, 108, 16, 76, 55, 375,..."

  ❌  10 goals WITHOUT qualifierId 25:

,source_match_id,period,minute,second,qualifier_ids
0,10d1132abu0fa9xolj05top3o,2,74,13,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,2,63,52,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,2,76,31,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,2,89,9,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,1,8,28,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,1,11,0,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,1,41,28,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,2,60,3,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,1,9,39,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,1,33,41,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

=================================================================
  qualifierId 26   —   Free kick
  Goals WITH: 8   |   Goals WITHOUT: 597
=================================================================

  ✅  10 goals WITH qualifierId 26:

,source_match_id,period,minute,second,qualifier_ids
0,1cg5aiu7phyw89gyr0m9hme50,2,81,57,"[102, 20, 328, 154, 120, 76, 230, 395, 18, 396..."
1,1d6oxum3q5ydyzsf48df1qas4,2,86,2,"[56, 282, 26, 458, 18, 472, 20, 103, 231, 280,..."
2,1r4k8mooxohtqr7vzjm29hul0,1,33,50,"[375, 472, 281, 282, 280, 231, 18, 56, 26, 122..."
3,1ts1vbi2mugv1401ifojdtqtw,2,68,3,"[374, 77, 18, 375, 458, 103, 26, 231, 281, 282..."
4,1wwdsnnj2m9ewz1d1mgt7y8k,1,36,30,"[26, 77, 230, 56, 18, 103, 102, 396, 375, 395,..."
5,du8jha9qxukb7ki17m3y3aj8,2,69,6,"[458, 18, 396, 26, 231, 395, 120, 81, 375, 374..."
6,fo7f0yq3c06q4hrw7vamnnro,2,48,29,"[121, 56, 395, 26, 458, 76, 375, 231, 72, 374,..."
7,m3rr5kwhsu6s770ey69xad5g,2,63,0,"[102, 26, 374, 77, 375, 18, 136, 396, 458, 103..."

  ❌  10 goals WITHOUT qualifierId 26:

,source_match_id,period,minute,second,qualifier_ids
0,10d1132abu0fa9xolj05top3o,2,74,13,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,2,63,52,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,2,76,31,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,2,89,9,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,1,8,28,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,1,11,0,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,1,41,28,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,2,60,3,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,1,9,39,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,1,33,41,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

=================================================================
  qualifierId 96   —   Corner situation
  Goals WITH: 0   |   Goals WITHOUT: 605
=================================================================

  ✅  10 goals WITH qualifierId 96:
  (no goals found for: WITH 96)

  ❌  10 goals WITHOUT qualifierId 96:

,source_match_id,period,minute,second,qualifier_ids
0,10d1132abu0fa9xolj05top3o,2,74,13,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
1,10qg7chtpoj0knqnvx2oduot0,2,63,52,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
2,10qg7chtpoj0knqnvx2oduot0,2,76,31,"[328, 102, 29, 374, 20, 231, 17, 214, 396, 55,..."
3,10qg7chtpoj0knqnvx2oduot0,2,89,9,"[29, 17, 136, 374, 375, 231, 103, 154, 102, 39..."
4,113wccwt50kebz0thqf0fxkpg,1,8,28,"[22, 230, 102, 17, 395, 468, 72, 103, 231, 154..."
5,113wccwt50kebz0thqf0fxkpg,1,11,0,"[468, 231, 396, 328, 375, 20, 154, 214, 55, 22..."
6,113wccwt50kebz0thqf0fxkpg,1,41,28,"[374, 396, 215, 29, 20, 22, 102, 138, 103, 64,..."
7,113wccwt50kebz0thqf0fxkpg,2,60,3,"[79, 72, 113, 56, 215, 64, 231, 374, 395, 138,..."
8,11hplskmrac4dwfmqv72f9nh0,1,9,39,"[103, 56, 395, 230, 55, 231, 72, 375, 18, 22, ..."
9,11hplskmrac4dwfmqv72f9nh0,1,33,41,"[396, 55, 102, 328, 230, 56, 395, 121, 29, 375..."

In [9]:
# ── Deep-dive: qualifierId 458 ────────────────────────────────────────────────

INSPECT_QID = 458

subset  = [s for s in shots if INSPECT_QID in s["qualifier_ids"]]
missing = [s for s in shots if INSPECT_QID not in s["qualifier_ids"]]
total   = len(shots)

print(f"qualifierId {INSPECT_QID}  —  {qual_name(INSPECT_QID, quals_mapping)}")
print(f"Appears on {len(subset):,} / {total:,} shot events ({len(subset)/total*100:.1f}%)\n")

# ── 0. Does qualifier 458 appear on non-shot events? ─────────────────────────
print("── 0. All event types carrying qualifierId 458 (full match scan) ───")
counts_by_type: Counter = Counter()
for fp in sorted(p for p in MATCHES_DIR.iterdir() if p.is_file() and not p.name.startswith(".")):
    try:
        data = extract_json_from_jsonp(fp)
    except Exception:
        continue
    for ev in data["liveData"]["event"]:
        qids = [q.get("qualifierId") for q in ev.get("qualifier", [])]
        if INSPECT_QID in qids:
            counts_by_type[ev.get("typeId")] += 1

KNOWN_TYPE_NAMES = {
    1: "Pass", 2: "Offside pass", 3: "Take on", 4: "Foul", 5: "Out",
    6: "Corner awarded", 7: "Tackle", 8: "Interception", 10: "Save",
    11: "Claim", 12: "Clearance", 13: "Miss", 14: "Post",
    15: "Attempt Saved", 16: "Goal", 17: "Card", 18: "Player off",
    19: "Player on", 32: "Start period", 34: "Team set up",
    40: "Other ball contact", 49: "Ball recovery", 55: "Ball touch",
    61: "Chance missed", -1: "Carry (synthetic)",
}

total_all = sum(counts_by_type.values())
print(f"  Events with qualifier 458 across ALL types: {total_all:,}\n")
rows_type = []
for tid, cnt in sorted(counts_by_type.items(), key=lambda x: -x[1]):
    rows_type.append({
        "typeId"    : tid,
        "type_name" : KNOWN_TYPE_NAMES.get(tid, f"typeId {tid}"),
        "count"     : cnt,
        "pct_of_all": f"{cnt/total_all*100:.1f}%",
        "is_shot"   : tid in SHOT_TYPE_IDS,
    })
display(pd.DataFrame(rows_type))

# ── 1. Which shot typeIds carry it? ──────────────────────────────────────────
print("\n── 1. Shot type breakdown ──────────────────────────────────────────")
type_dist = Counter(f"{s['type_id']} ({s['type_name']})" for s in subset)
for label, cnt in type_dist.most_common():
    print(f"  {cnt:>4}x  ({cnt/len(subset)*100:.1f}%)  {label}")

# ── 2. Qualifier value distribution ──────────────────────────────────────────
print("\n── 2. Qualifier value distribution ─────────────────────────────────")
val_dist = Counter(s["qualifier_vals"].get(INSPECT_QID) for s in subset)
for val, cnt in val_dist.most_common(15):
    print(f"  {cnt:>4}x  {repr(val)}")

# ── 3. Top co-occurring qualifiers ───────────────────────────────────────────
print("\n── 3. Top co-occurring qualifiers (on shots WITH 458) ──────────────")
cooccur: Counter = Counter()
for s in subset:
    for other in s["qualifier_ids"]:
        if other != INSPECT_QID:
            cooccur[other] += 1
for other_qid, cnt in cooccur.most_common(20):
    print(f"  {cnt:>4}x  ({cnt/len(subset)*100:.1f}%)  qualifierId {other_qid:>4}  —  {qual_name(other_qid, quals_mapping)}")

# ── 4. Companion analysis: P(458 | qualifier X) vs P(458 | ¬qualifier X) ─────
# Each row answers: "of all shot events that carry qualifier X, what % also have 458?"
# This is the reverse of the old table, which asked "of 458-events, how many have X?"
# Example reading: P(458 | Penalty) = 100% means every penalty shot carries 458.
# Baseline: 458 appears on ~25.9% of all shots, so lift > 1 means X predicts 458.
print("\n── 4. Companion analysis ────────────────────────────────────────────")
print(f"  Reading: 'P(458|X)' = among shots WITH qualifier X, % that also carry 458")
print(f"  Baseline P(458) = {len(subset)/total*100:.1f}%  (458 appears on this share of all shots)\n")

cooccur_missing: Counter = Counter()
for s in missing:
    for other in s["qualifier_ids"]:
        cooccur_missing[other] += 1

rows = []
all_qids = set(cooccur.keys()) | set(cooccur_missing.keys())
for qid in all_qids:
    cnt_with_both = cooccur.get(qid, 0)        # has X  AND has 458
    cnt_x_no_458  = cooccur_missing.get(qid, 0) # has X  but  no 458
    cnt_x_total   = cnt_with_both + cnt_x_no_458

    cnt_458_no_x  = len(subset) - cnt_with_both  # no X  but has 458
    cnt_no_x      = total - cnt_x_total           # no X  (with or without 458)

    pct_458_if_x    = cnt_with_both / cnt_x_total * 100 if cnt_x_total > 0 else 0.0
    pct_458_if_no_x = cnt_458_no_x  / cnt_no_x   * 100 if cnt_no_x    > 0 else 0.0
    lift = pct_458_if_x / pct_458_if_no_x if pct_458_if_no_x > 0 else float("inf")

    rows.append({
        "qualifierId"  : qid,
        "name"         : qual_name(qid, quals_mapping),
        "shots_with_X" : cnt_x_total,
        "P(458|X)"     : f"{pct_458_if_x:.1f}%",
        "P(458|no X)"  : f"{pct_458_if_no_x:.1f}%",
        "lift"         : round(lift, 2),
    })

df_lift = (
    pd.DataFrame(rows)
    .sort_values("lift", ascending=False)
    .reset_index(drop=True)
)
display(df_lift.head(25))

# ── 5. Outcome distribution ───────────────────────────────────────────────────
print("\n── 5. Outcome distribution ─────────────────────────────────────────")
out_dist = Counter(s["outcome"] for s in subset)
for val, cnt in out_dist.most_common():
    print(f"  outcome={val}  {cnt:>4}x  ({cnt/len(subset)*100:.1f}%)")

# ── 6. Sample rows ────────────────────────────────────────────────────────────
print(f"\n── 6. Sample events with qualifierId {INSPECT_QID} (up to 15) ────────")
display(
    pd.DataFrame(subset[:15])[[
        "match", "type_name", "period", "minute", "outcome", "x", "y", "qualifier_ids"
    ]]
)

qualifierId 458  —  *** NOT IN MAPPING ***
Appears on 1,502 / 5,793 shot events (25.9%)

── 0. All event types carrying qualifierId 458 (full match scan) ───
  Events with qualifier 458 across ALL types: 1,522

   typeId      type_name  count pct_of_all  is_shot
0      15  Attempt Saved    752      49.4%     True
1      13           Miss    538      35.3%     True
2      16           Goal    184      12.1%     True
3      14           Post     28       1.8%     True
4      43      typeId 43     10       0.7%    False
5      84      typeId 84     10       0.7%    False

── 1. Shot type breakdown ──────────────────────────────────────────
   752x  (50.1%)  15 (Attempt Saved)
   538x  (35.8%)  13 (Miss)
   184x  (12.3%)  16 (Goal)
    28x  (1.9%)  14 (Post)

── 2. Qualifier value distribution ─────────────────────────────────
  1502x  None

── 3. Top co-occurring qualifiers (on shots WITH 458) ──────────────
  1502x  (100.0%)  qualifierId  103  —  Goal mouth z co-ordinate
  1502x  (100.0%)  qualifierId  102  —  Goal mouth y co-ordinate
  1502x  (100.0%)  qualifierId   56  —  Zone
  1204x  (80.2%)  qualifierId  231  —  GK Y Coordinate
  1204x  (80.2%)  qualifierId  230  —  GK X Coordinate
   870x  (57.9%)  qualifierId  146  —  Blocked x co-ordinate
   870x  (57.9%)  qualifierId  147  —  Blocked y co-ordinate
   847x  (56.4%)  qualifierId   20  —  Right footed
   787x  (52.4%)  qualifierId   22  —  Regular play
   724x  (48.2%)  qualifierId  233  —  Opposite related event ID
   720x  (47.9%)  qualifierId  328  —  First Time
   689x  (45.9%)  qualifierId   18  —  Out of box-centre
   606x  (40.3%)  qualifierId  215  —  Individual Play
   583x  (38.8%)  qualifierId   72  —  Left footed
   462x  (30.8%)  qualifierId   17  —  Box-centre
   450x  (30.0%)  qualifierId   82  —  Blocked
   448x  (29.8%)  qualifierId   78  —  Low centre
   304x  (20.2%)  qualifierId  108  —  Volley
   273x  (18.2%)  qualifierId   25  —  From corner
   267x  (17.8%)  qualifierId  214  —  Big Chance

── 4. Companion analysis ────────────────────────────────────────────
  Reading: 'P(458|X)' = among shots WITH qualifier X, % that also carry 458
  Baseline P(458) = 25.9%  (458 appears on this share of all shots)

,qualifierId,name,shots_with_X,P(458|X),P(458|no X),lift
0,102,Goal mouth y co-ordinate,5793,25.9%,0.0%,inf
1,56,Zone,5793,25.9%,0.0%,inf
2,103,Goal mouth z co-ordinate,5793,25.9%,0.0%,inf
3,9,Penalty,85,100.0%,24.8%,4.03
4,390,*** NOT IN MAPPING ***,85,100.0%,24.8%,4.03
5,353,*** NOT IN MAPPING ***,85,100.0%,24.8%,4.03
6,26,Free kick,150,96.7%,24.0%,4.02
7,487,*** NOT IN MAPPING ***,3,100.0%,25.9%,3.86
8,280,Fantasy Assist Type,116,88.8%,24.6%,3.60
9,281,Fantasy Assisted By,116,88.8%,24.6%,3.60
10,282,Fantasy Assist Team,116,88.8%,24.6%,3.60
11,472,*** NOT IN MAPPING ***,116,88.8%,24.6%,3.60
12,69,Out of box-deep left,14,78.6%,25.8%,3.05
13,66,Out of box-deep right,7,71.4%,25.9%,2.76
14,108,Volley,619,49.1%,23.2%,2.12
15,468,*** NOT IN MAPPING ***,243,49.0%,24.9%,1.97
16,71,35+ left,2,50.0%,25.9%,1.93
17,19,35+ centre,45,48.9%,25.7%,1.90
18,139,Own Player,57,47.4%,25.7%,1.84
19,101,Saved off line,38,44.7%,25.8%,1.73
20,18,Out of box-centre,1995,34.5%,21.4%,1.61
21,113,Strong,81,40.7%,25.7%,1.58
22,314,*** NOT IN MAPPING ***,11,36.4%,25.9%,1.40
23,121,Swerve Right,230,34.8%,25.6%,1.36
24,20,Right footed,2868,29.5%,22.4%,1.32

── 5. Outcome distribution ─────────────────────────────────────────
  outcome=1  1502x  (100.0%)

── 6. Sample events with qualifierId 458 (up to 15) ────────

,match,type_name,period,minute,outcome,x,y,qualifier_ids
0,10d1132abu0fa9xolj05top3o,Miss,1,4,1,77.2,55.8,"[328, 103, 215, 231, 102, 160, 230, 77, 72, 45..."
1,10d1132abu0fa9xolj05top3o,Attempt Saved,1,34,1,74.3,35.8,"[102, 328, 215, 103, 24, 146, 20, 82, 18, 233,..."
2,10d1132abu0fa9xolj05top3o,Attempt Saved,1,47,1,92.9,32.9,"[56, 102, 20, 233, 22, 147, 103, 78, 458, 328,..."
3,10d1132abu0fa9xolj05top3o,Attempt Saved,2,54,1,90.6,39.3,"[22, 15, 102, 328, 233, 56, 147, 458, 146, 103..."
4,10d1132abu0fa9xolj05top3o,Attempt Saved,2,61,1,90.2,48.5,"[146, 458, 147, 108, 103, 231, 233, 25, 17, 10..."
5,10d1132abu0fa9xolj05top3o,Attempt Saved,2,61,1,79.9,41.5,"[231, 102, 146, 458, 147, 215, 82, 230, 18, 56..."
6,10d1132abu0fa9xolj05top3o,Attempt Saved,2,74,1,92.0,42.7,"[146, 15, 214, 147, 102, 56, 22, 233, 328, 17,..."
7,10d1132abu0fa9xolj05top3o,Goal,2,74,1,96.2,54.6,"[20, 472, 16, 328, 214, 395, 396, 22, 458, 281..."
8,10d1132abu0fa9xolj05top3o,Attempt Saved,2,80,1,76.6,31.1,"[18, 102, 146, 26, 103, 56, 458, 78, 147, 120,..."
9,10d1132abu0fa9xolj05top3o,Attempt Saved,2,92,1,96.8,69.5,"[20, 458, 147, 146, 22, 233, 102, 468, 103, 65..."
10,10qg7chtpoj0knqnvx2oduot0,Miss,1,3,1,96.4,62.2,"[56, 230, 231, 102, 468, 458, 61, 74, 328, 103..."
11,10qg7chtpoj0knqnvx2oduot0,Goal,2,63,1,88.5,50.0,"[458, 17, 280, 76, 374, 214, 396, 231, 390, 39..."
12,113wccwt50kebz0thqf0fxkpg,Miss,1,32,1,75.7,29.1,"[73, 22, 56, 230, 103, 20, 458, 215, 231, 102,..."
13,113wccwt50kebz0thqf0fxkpg,Attempt Saved,1,38,1,91.4,44.0,"[108, 233, 147, 56, 20, 146, 78, 25, 82, 103, ..."
14,113wccwt50kebz0thqf0fxkpg,Attempt Saved,1,38,1,81.6,37.8,"[103, 230, 25, 102, 18, 233, 458, 231, 146, 78..."