# Opta Event TypeId Audit

Scans every JSONP match file under `data/raw/PRD/2025-2026/matches/` and compares
every `typeId` found in the raw data against the mapping we have in `data/mapping/opta-events.js`.

**What this tells you:**
- `In files, NOT in mapping` → new / undocumented event types we need to investigate
- `In mapping, NOT in files` → event types in our reference that we haven't seen in the data yet
- Full frequency table of every typeId observed

In [7]:
import json
import re
from pathlib import Path
from collections import defaultdict

import pandas as pd

# ── Configure paths (relative to the notebooks/ directory) ─────────────────
ROOT          = Path("..")
MATCHES_DIR   = ROOT / "data" / "raw" / "PRD" / "2025-2026" / "matches"
EVENTS_JS     = ROOT / "data" / "mapping" / "opta-events.js"

print(f"Matches dir : {MATCHES_DIR.resolve()}")
print(f"  exists    : {MATCHES_DIR.exists()}")
print(f"Events JS   : {EVENTS_JS.resolve()}")
print(f"  exists    : {EVENTS_JS.exists()}")

Matches dir : C:\Users\Usuario\OneDrive\football-analytics-research\data\raw\PRD\2025-2026\matches
  exists    : True
Events JS   : C:\Users\Usuario\OneDrive\football-analytics-research\data\mapping\opta-events.js
  exists    : True

In [8]:
# ── 1. Load the opta-events.js mapping ─────────────────────────────────────

def load_events_mapping(js_path: Path) -> dict[int, str]:
    """
    Parse the OptaEvents JS file and return {typeId (int): label (str)}.

    Uses the same regex as parser.py's load_mapping_file():
        var optaEventCodes = {1: 'Pass', 2: 'Offside Pass', ...};
    """
    content = js_path.read_text(encoding="utf-8")

    # ── Debug: print first 300 chars so you can see the actual format ──────
    print("--- First 300 chars of file ---")
    print(repr(content[:300]))
    print("--- End preview ---\n")

    # ── Same regex used in parser.py load_mapping_file() ───────────────────
    match = re.search(r'var\s+\w+\s*=\s*(\{.*\});?', content, re.DOTALL)
    if not match:
        raise ValueError(f"Could not extract mapping dict from {js_path}")

    js_obj = match.group(1)

    # Quote ALL unquoted identifier keys (matches both numeric and word keys)
    js_obj = re.sub(r'(\w+):', r'"\1":', js_obj)
    # Single-quoted values → double-quoted
    js_obj = re.sub(r"'([^']*?)'", r'"\1"', js_obj)
    # Remove trailing commas before } (invalid JSON)
    js_obj = re.sub(r',\s*\}', '}', js_obj)

    return {int(k): v for k, v in json.loads(js_obj).items()}


events_mapping = load_events_mapping(EVENTS_JS)
print(f"Loaded {len(events_mapping)} event types from opta-events.js")
print("\nFirst 10 entries:")
for tid, label in sorted(events_mapping.items())[:10]:
    print(f"  {tid:>4}  {label}")

--- First 300 chars of file ---
'var optaEventCodes = {\n1:{name:"Pass",description:"Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists"},\n2:{name:"Offside Pass",description:"Attempted pass made to a player who is in an offside position"},\n3:{name:"Take On",description:"Attempt'
--- End preview ---

Loaded 67 event types from opta-events.js

First 10 entries:
     1  {'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'}
     2  {'name': 'Offside Pass', 'description': 'Attempted pass made to a player who is in an offside position'}
     3  {'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'}
     4  {'name': 'Foul', 'description': 'This event is shown when a foul is committed resulting in a free kick'}
     5  {'name': 'Out', 'description': 'Shown each time the ball goes out of play for a throw-in or goal kick'}
     6  {'name': 'Corner Awarded', 'description': 'Ball goes out of play for a corner kick'}
     7  {'name': 'Tackle', 'description': 'Tackle = dispossesses an opponent of the ball - Outcome 1 = win & retain possession or out of play, 0 = win tackle but not possession'}
     8  {'name': 'Interception', 'description': 'When a player intercepts any pass event between opposition players and prevents the ball reaching its target. Cannot be a clearance.'}
     9  {'name': 'Turnover', 'description': 'Unforced error / loss of possession - i.e. bad control of ball  NO LONGER USED (Replaced with Unsuccessful Touch + Overrun)'}
    10  {'name': 'Save', 'description': 'Goalkeeper event; saving a shot on goal. Can also be an outfield player event with qualifier 94 for blocked shot'}

In [9]:
# ── 2. Parse JSONP files ────────────────────────────────────────────────────

def extract_json_from_jsonp(path: Path) -> dict:
    """
    Strip the JSONP wrapper (hash prefix + outer function call) and return
    the inner dict. Handles both:
        W3c016d8247...({...})
        someCallback({...})
    """
    raw = path.read_text(encoding="utf-8")
    start = raw.index("{")
    payload = raw[start:].rstrip()
    if payload.endswith(")"):
        payload = payload[:-1]
    return json.loads(payload)


def scan_match_files(matches_dir: Path) -> tuple[dict[int, int], list[str], list[str]]:
    """
    Walk every file in matches_dir, extract all typeIds, and return:
      - type_id_counts  : {typeId: total_occurrence_count across all files}
      - errors          : list of files that failed to parse
      - processed       : list of successfully processed filenames
    """
    type_id_counts: dict[int, int] = defaultdict(int)
    errors: list[str] = []
    processed: list[str] = []

    # Accept both .json and extensionless JSONP files
    all_files = [
        p for p in matches_dir.iterdir()
        if p.is_file() and not p.name.startswith(".")
    ]

    if not all_files:
        print(f"WARNING: No files found in {matches_dir}")
        return type_id_counts, errors, processed

    print(f"Found {len(all_files)} file(s) to scan...")

    for fp in sorted(all_files):
        try:
            data   = extract_json_from_jsonp(fp)
            events = data["liveData"]["event"]
            for event in events:
                tid = event.get("typeId")
                if tid is not None:
                    type_id_counts[int(tid)] += 1
            processed.append(fp.name)
        except Exception as exc:
            errors.append(f"{fp.name}: {exc}")

    return dict(type_id_counts), errors, processed


type_id_counts, parse_errors, processed_files = scan_match_files(MATCHES_DIR)

print(f"\n✓ Processed : {len(processed_files)} files")
print(f"✗ Errors    : {len(parse_errors)} files")
if parse_errors:
    print("\nFailed files:")
    for e in parse_errors:
        print(f"  {e}")

Found 210 file(s) to scan...

✓ Processed : 210 files
✗ Errors    : 0 files

In [10]:
# ── 3. Compare: files vs mapping ────────────────────────────────────────────

ids_in_files   = set(type_id_counts.keys())
ids_in_mapping = set(events_mapping.keys())

new_ids        = ids_in_files - ids_in_mapping   # ← IMPORTANT: seen but not documented
unseen_ids     = ids_in_mapping - ids_in_files   # in mapping but never seen in data
common_ids     = ids_in_files & ids_in_mapping

print("=" * 55)
print(f"  typeIds in match files       : {len(ids_in_files)}")
print(f"  typeIds in opta-events.js    : {len(ids_in_mapping)}")
print(f"  Matched (in both)            : {len(common_ids)}")
print("=" * 55)
print(f"  ⚠  In FILES, NOT in mapping  : {len(new_ids)}")
print(f"  ℹ  In MAPPING, NOT in files  : {len(unseen_ids)}")
print("=" * 55)

=======================================================
  typeIds in match files       : 56
  typeIds in opta-events.js    : 67
  Matched (in both)            : 50
=======================================================
  ⚠  In FILES, NOT in mapping  : 6
  ℹ  In MAPPING, NOT in files  : 17
=======================================================

In [11]:
# ── 4. Detail — IDs in files but NOT in mapping (action required) ───────────

if new_ids:
    print(f"\n🚨  {len(new_ids)} typeId(s) found in match data that are NOT in opta-events.js:\n")
    rows = [
        {"typeId": tid, "occurrences": type_id_counts[tid], "label_in_mapping": "*** MISSING ***"}
        for tid in sorted(new_ids)
    ]
    df_new = pd.DataFrame(rows)
    display(df_new)
else:
    print("\n✅  All typeIds in match data are present in opta-events.js — no new event types found.")

🚨  6 typeId(s) found in match data that are NOT in opta-events.js:

   typeId  occurrences label_in_mapping
0      75            1  *** MISSING ***
1      79            6  *** MISSING ***
2      80          283  *** MISSING ***
3      81           59  *** MISSING ***
4      83         5682  *** MISSING ***
5      84           63  *** MISSING ***

In [12]:
# ── 5. Detail — IDs in mapping but never seen (informational) ──────────────

if unseen_ids:
    print(f"\nℹ  {len(unseen_ids)} typeId(s) in opta-events.js that were NOT seen in any match file:")
    print("   (These may be rare events, deprecated codes, or from other competitions.)\n")
    rows = [
        {"typeId": tid, "label": events_mapping[tid]}
        for tid in sorted(unseen_ids)
    ]
    df_unseen = pd.DataFrame(rows)
    display(df_unseen)
else:
    print("\n✅  Every typeId in opta-events.js has been observed at least once in match data.")

ℹ  17 typeId(s) in opta-events.js that were NOT seen in any match file:
   (These may be rare events, deprecated codes, or from other competitions.)

    typeId                                              label
0        9  {'name': 'Turnover', 'description': 'Unforced ...
1       21  {'name': 'Player returns', 'description': 'Pla...
2       23  {'name': 'Goalkeeper becomes player', 'descrip...
3       24  {'name': 'Condition change', 'description': 'C...
4       25  {'name': 'Official change', 'description': 'Re...
5       35  {'name': 'Player changed position', 'descripti...
6       36  {'name': 'Player changed Jersey number', 'desc...
7       38  {'name': 'Temp_Goal', 'description': 'Goal has...
8       39  {'name': 'Temp_Attempt', 'description': 'Shot ...
9       47  {'name': 'Rescinded card', 'description': 'Thi...
10      63  {'name': 'Temp_Save', 'description': 'An event...
11      64  {'name': 'Resume', 'description': 'Match resum...
12      66  {'name': 'Possession Data', 'description': 'Po...
13      67  {'name': '50/50', 'description': 'New duel - 2...
14      69  {'name': 'Failed to Block', 'description': 'Ne...
15      72  {'name': 'Caught Offside', 'description': 'New...
16      73  {'name': 'Other Ball Contact', 'description': ...

In [13]:
# ── 6. Full frequency table ─────────────────────────────────────────────────

rows = []
for tid in sorted(type_id_counts.keys()):
    rows.append({
        "typeId"        : tid,
        "label"         : events_mapping.get(tid, "*** NOT IN MAPPING ***"),
        "occurrences"   : type_id_counts[tid],
        "in_mapping"    : tid in ids_in_mapping,
    })

df_all = (
    pd.DataFrame(rows)
    .sort_values("occurrences", ascending=False)
    .reset_index(drop=True)
)

print(f"\nFull event typeId frequency table ({len(df_all)} distinct typeIds seen):\n")
display(df_all)

Full event typeId frequency table (56 distinct typeIds seen):

,typeId,label,occurrences,in_mapping
0,1,"{'name': 'Pass', 'description': 'Any pass atte...",201218,True
1,5,"{'name': 'Out', 'description': 'Shown each tim...",22496,True
2,49,"{'name': 'Ball recovery', 'description': 'Team...",17158,True
3,61,"{'name': 'Ball touch', 'description': 'Used wh...",15152,True
4,44,"{'name': 'Aerial', 'description': 'Aerial duel...",11026,True
5,12,"{'name': 'Clearance', 'description': 'Player u...",10815,True
6,4,"{'name': 'Foul', 'description': 'This event is...",10560,True
7,3,"{'name': 'Take On', 'description': 'Attempted ...",7996,True
8,43,"{'name': 'Deleted event', 'description': 'Even...",7903,True
9,7,"{'name': 'Tackle', 'description': 'Tackle = di...",7062,True
10,83,*** NOT IN MAPPING ***,5682,False
11,6,"{'name': 'Corner Awarded', 'description': 'Bal...",4104,True
12,50,"{'name': 'Dispossessed', 'description': 'Playe...",3514,True
13,8,"{'name': 'Interception', 'description': 'When ...",3316,True
14,45,"{'name': 'Challenge', 'description': 'When a p...",3242,True
15,74,"{'name': 'Blocked Pass', 'description': 'Defen...",3044,True
16,15,"{'name': 'Attempt Saved', 'description': 'Shot...",2693,True
17,10,"{'name': 'Save', 'description': 'Goalkeeper ev...",2668,True
18,52,"{'name': 'Keeper pick-up', 'description': 'Goa...",2480,True
19,19,"{'name': 'Player on', 'description': 'Player c...",1974,True
20,18,"{'name': 'Player off', 'description': 'Player ...",1974,True
21,13,"{'name': 'Miss', 'description': 'Any shot on g...",1972,True
22,28,"{'name': 'End delay', 'description': 'Used whe...",1301,True
23,27,"{'name': 'Start delay', 'description': 'Used w...",1301,True
24,30,"{'name': 'End', 'description': 'End of a match...",1260,True
25,17,"{'name': 'Card', 'description': 'Bookings; wil...",1018,True
26,32,"{'name': 'Start', 'description': 'Start of a m...",840,True
27,55,"{'name': 'Offside provoked', 'description': 'A...",792,True
28,2,"{'name': 'Offside Pass', 'description': 'Attem...",792,True
29,40,"{'name': 'Formation change', 'description': 'T...",693,True
30,16,"{'name': 'Goal', 'description': 'All goals'}",549,True
31,68,"{'name': 'Referee Drop Ball', 'description': '...",500,True
32,37,"{'name': 'Collection End', 'description': 'Eve...",420,True
33,34,"{'name': 'Team set up', 'description': 'Team l...",420,True
34,70,"{'name': 'Injury Time Announcement', 'descript...",420,True
35,59,"{'name': 'Keeper Sweeper', 'description': 'Whe...",341,True
36,11,"{'name': 'Claim', 'description': 'Goalkeeper e...",320,True
37,51,"{'name': 'Error', 'description': 'Mistake by p...",286,True
38,80,*** NOT IN MAPPING ***,283,False
39,56,"{'name': 'Shield ball opp', 'description': 'De...",266,True
40,41,"{'name': 'Punch', 'description': 'Goalkeeper e...",180,True
41,14,"{'name': 'Post', 'description': 'Whenever the ...",91,True
42,65,"{'name': 'Contentious referee decision', 'desc...",83,True
43,58,"{'name': 'Penalty faced', 'description': 'Goal...",76,True
44,84,*** NOT IN MAPPING ***,63,False
45,54,"{'name': 'Smother', 'description': 'Goalkeeper...",59,True
46,81,*** NOT IN MAPPING ***,59,False
47,42,"{'name': 'Good Skill', 'description': 'A playe...",48,True
48,57,"{'name': 'Foul throw-in', 'description': 'A th...",28,True
49,60,"{'name': 'Chance missed', 'description': 'Used...",19,True
50,71,"{'name': 'Coach Setup', 'description': 'Coach ...",8,True
51,79,*** NOT IN MAPPING ***,6,False
52,53,"{'name': 'Cross not claimed', 'description': '...",4,True
53,20,"{'name': 'Player retired', 'description': 'Pla...",2,True
54,22,"{'name': 'Player becomes goalkeeper', 'descrip...",1,True
55,75,*** NOT IN MAPPING ***,1,False

In [14]:
# ── 7. Summary card ─────────────────────────────────────────────────────────

total_events = sum(type_id_counts.values())

print("\n" + "=" * 55)
print(" AUDIT SUMMARY")
print("=" * 55)
print(f"  Match files scanned          : {len(processed_files)}")
print(f"  Total events parsed          : {total_events:,}")
print(f"  Distinct typeIds seen        : {len(ids_in_files)}")
print(f"  Covered by opta-events.js   : {len(common_ids)}")
print(f"  ⚠  NEW (not in mapping)     : {len(new_ids)}", end="")
print("  ← update opta-events.js!" if new_ids else "")
print(f"  ℹ  Unseen (in mapping only) : {len(unseen_ids)}")
print("=" * 55)

if not new_ids:
    print("\n✅  Your opta-events.js is fully consistent with the match data.")
else:
    print(f"\n⚠  ACTION REQUIRED: {len(new_ids)} typeId(s) missing from opta-events.js.")
    print("   Check the table in cell 4 above and add the missing entries.")

=======================================================
 AUDIT SUMMARY
=======================================================
  Match files scanned          : 210
  Total events parsed          : 360,579
  Distinct typeIds seen        : 56
  Covered by opta-events.js   : 50
  ⚠  NEW (not in mapping)     : 6  ← update opta-events.js!
  ℹ  Unseen (in mapping only) : 17
=======================================================

⚠  ACTION REQUIRED: 6 typeId(s) missing from opta-events.js.
   Check the table in cell 4 above and add the missing entries.

In [15]:
# ── Neighbour context for unknown typeIds ───────────────────────────────────
# For each unknown typeId, samples up to MAX_SAMPLES occurrences and shows
# what event comes immediately before and after it in the period sequence.
# Filters to only typeIds above MIN_OCCURRENCES (the ones worth investigating).

from collections import defaultdict

MIN_OCCURRENCES = 50   # only inspect typeIds that appear this many times or more
MAX_SAMPLES     = 20   # max example rows to collect per unknown typeId

# ── Which unknown IDs are worth investigating? ──────────────────────────────
unknown_ids_to_check = {
    tid for tid in new_ids                    # new_ids = from previous cell
    if type_id_counts.get(tid, 0) >= MIN_OCCURRENCES
}
print(f"Investigating {len(unknown_ids_to_check)} unknown typeId(s) with >= {MIN_OCCURRENCES} occurrences:")
print(f"  {sorted(unknown_ids_to_check)}\n")


def label(tid, mapping):
    """Return 'typeId (Label)' or 'typeId (???)' if unknown."""
    if tid is None:
        return "None"
    name = mapping.get(tid, "???")
    return f"{tid} ({name})"


# ── Collect neighbour samples ───────────────────────────────────────────────
# neighbours[typeId] = list of {prev, target, next, minute, period, match}
neighbours: dict[int, list[dict]] = defaultdict(list)

all_files = [
    p for p in MATCHES_DIR.iterdir()
    if p.is_file() and not p.name.startswith(".")
]

for fp in sorted(all_files):
    # Stop early once we have enough samples for all targets
    if all(len(neighbours[tid]) >= MAX_SAMPLES for tid in unknown_ids_to_check):
        break
    try:
        data   = extract_json_from_jsonp(fp)
        events = data["liveData"]["event"]
    except Exception:
        continue

    # Group events by period to avoid bleeding across half-time boundary
    by_period: dict[int, list[dict]] = defaultdict(list)
    for ev in events:
        by_period[ev.get("periodId", 0)].append(ev)

    for period_id, period_events in by_period.items():
        for i, ev in enumerate(period_events):
            tid = ev.get("typeId")
            if tid not in unknown_ids_to_check:
                continue
            if len(neighbours[tid]) >= MAX_SAMPLES:
                continue

            prev_ev = period_events[i - 1] if i > 0 else None
            next_ev = period_events[i + 1] if i < len(period_events) - 1 else None

            neighbours[tid].append({
                "match"       : fp.name,
                "period"      : period_id,
                "minute"      : ev.get("timeMin"),
                "prev_typeId" : prev_ev.get("typeId") if prev_ev else None,
                "target_typeId": tid,
                "next_typeId" : next_ev.get("typeId") if next_ev else None,
                "qualifiers"  : [q.get("qualifierId") for q in ev.get("qualifier", [])],
                "outcome"     : ev.get("outcome"),
                "x"           : ev.get("x"),
                "y"           : ev.get("y"),
            })

print(f"Samples collected per typeId:")
for tid in sorted(unknown_ids_to_check):
    print(f"  typeId {tid}: {len(neighbours[tid])} samples")

Investigating 4 unknown typeId(s) with >= 50 occurrences:
  [80, 81, 83, 84]

Samples collected per typeId:
  typeId 80: 20 samples
  typeId 81: 20 samples
  typeId 83: 20 samples
  typeId 84: 20 samples

In [16]:
# ── Display neighbour analysis per unknown typeId ───────────────────────────

for tid in sorted(unknown_ids_to_check):
    samples = neighbours[tid]
    if not samples:
        continue

    total = type_id_counts.get(tid, 0)
    print("\n" + "═" * 65)
    print(f"  typeId {tid} — ??? (NOT IN MAPPING)   |   {total:,} total occurrences")
    print("═" * 65)

    # ── Frequency table: what comes before? ────────────────────────────────
    from collections import Counter
    prev_counts = Counter(s["prev_typeId"] for s in samples)
    next_counts = Counter(s["next_typeId"] for s in samples)

    print("\n  PREV event (what triggers this event):")
    for ptid, cnt in prev_counts.most_common():
        print(f"    {cnt:>3}x   {label(ptid, events_mapping)}")

    print("\n  NEXT event (what follows this event):")
    for ntid, cnt in next_counts.most_common():
        print(f"    {cnt:>3}x   {label(ntid, events_mapping)}")

    # ── Qualifier IDs seen on this event ───────────────────────────────────
    all_quals = [q for s in samples for q in s["qualifiers"]]
    qual_counts = Counter(all_quals)
    if qual_counts:
        print("\n  Qualifier IDs on this event (most common first):")
        for qid, cnt in qual_counts.most_common(10):
            print(f"    {cnt:>3}x   qualifierId {qid}")
    else:
        print("\n  No qualifiers found on sampled events.")

    # ── outcome distribution ────────────────────────────────────────────────
    outcome_counts = Counter(s["outcome"] for s in samples)
    print(f"\n  Outcome distribution: {dict(outcome_counts)}")

    # ── Sample rows table ───────────────────────────────────────────────────
    df_samples = pd.DataFrame(samples)[[
        "match", "period", "minute", "prev_typeId", "target_typeId", "next_typeId", "qualifiers", "outcome"
    ]].copy()
    df_samples["prev"]   = df_samples["prev_typeId"].apply(lambda t: label(t, events_mapping))
    df_samples["target"] = df_samples["target_typeId"].apply(lambda t: label(t, events_mapping))
    df_samples["next"]   = df_samples["next_typeId"].apply(lambda t: label(t, events_mapping))
    display(
        df_samples[["match", "period", "minute", "prev", "target", "next", "qualifiers", "outcome"]]
        .head(MAX_SAMPLES)
    )

═════════════════════════════════════════════════════════════════
  typeId 80 — ??? (NOT IN MAPPING)   |   283 total occurrences
═════════════════════════════════════════════════════════════════

  PREV event (what triggers this event):
     16x   52 ({'name': 'Keeper pick-up', 'description': 'Goalkeeper event; picks up the ball'})
      3x   11 ({'name': 'Claim', 'description': 'Goalkeeper event; catching a crossed ball'})
      1x   43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})

  NEXT event (what follows this event):
     20x   1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})

  Qualifier IDs on this event (most common first):
      3x   qualifierId 189

  Outcome distribution: {0: 19, 1: 1}

,match,period,minute,prev,target,next,qualifiers,outcome
0,10d1132abu0fa9xolj05top3o,1,36,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
1,10d1132abu0fa9xolj05top3o,2,52,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
2,10d1132abu0fa9xolj05top3o,2,76,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
3,10d1132abu0fa9xolj05top3o,2,87,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
4,10qg7chtpoj0knqnvx2oduot0,1,24,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
5,11hplskmrac4dwfmqv72f9nh0,2,61,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
6,11uxeay5z2isuekqd9fq0usyc,1,20,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
7,11uxeay5z2isuekqd9fq0usyc,1,29,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
8,1288ajju0cadnuxxhvkal1mok,1,50,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[189],0
9,12zi2fz6nuyhye00alaymbms4,1,40,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
10,12zi2fz6nuyhye00alaymbms4,1,41,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[189],0
11,13d50vdn5ecuddcpg1cvdrq50,2,80,"11 ({'name': 'Claim', 'description': 'Goalkeep...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
12,13qwzalezgy8gxih0ube0ap78,1,1,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
13,13qwzalezgy8gxih0ube0ap78,1,9,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
14,13qwzalezgy8gxih0ube0ap78,1,13,"43 ({'name': 'Deleted event', 'description': '...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
15,13qwzalezgy8gxih0ube0ap78,1,40,"11 ({'name': 'Claim', 'description': 'Goalkeep...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[189],0
16,13qwzalezgy8gxih0ube0ap78,2,46,"11 ({'name': 'Claim', 'description': 'Goalkeep...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
17,144g7b7ez101gt3yczm0yblzo,1,31,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],1
18,144g7b7ez101gt3yczm0yblzo,2,96,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0
19,14ia91hr21lnjto1f2uga5f6c,1,42,"52 ({'name': 'Keeper pick-up', 'description': ...",80 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[],0

═════════════════════════════════════════════════════════════════
  typeId 81 — ??? (NOT IN MAPPING)   |   59 total occurrences
═════════════════════════════════════════════════════════════════

  PREV event (what triggers this event):
     11x   1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
      4x   61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
      2x   12 ({'name': 'Clearance', 'description': 'Player under pressure hits the ball clear of the defensive zone or/and out of play'})
      1x   74 ({'name': 'Blocked Pass', 'description': 'Defender is close to player in possession and blocks a pass. Different from interception which is where the player has moved to intercept.'})
      1x   13 ({'name': 'Miss', 'description': 'Any shot on goal which goes wide or over the goal'})
      1x   7 ({'name': 'Tackle', 'description': 'Tackle = dispossesses an opponent of the ball - Outcome 1 = win & retain possession or out of play, 0 = win tackle but not possession'})

  NEXT event (what follows this event):
      9x   5 ({'name': 'Out', 'description': 'Shown each time the ball goes out of play for a throw-in or goal kick'})
      3x   6 ({'name': 'Corner Awarded', 'description': 'Ball goes out of play for a corner kick'})
      3x   1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
      3x   27 ({'name': 'Start delay', 'description': 'Used when there is a stoppage in play such as a player injury'})
      1x   49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})
      1x   45 ({'name': 'Challenge', 'description': 'When a player fails to win the ball as an opponent successfully dribbles past them'})

  Qualifier IDs on this event (most common first):
     15x   qualifierId 380
      5x   qualifierId 138
      3x   qualifierId 275
      1x   qualifierId 274
      1x   qualifierId 273

  Outcome distribution: {0: 20}

,match,period,minute,prev,target,next,qualifiers,outcome
0,10qg7chtpoj0knqnvx2oduot0,2,58,"61 ({'name': 'Ball touch', 'description': 'Use...",81 (???),"6 ({'name': 'Corner Awarded', 'description': '...",[380],0
1,113wccwt50kebz0thqf0fxkpg,1,40,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...",[380],0
2,1288ajju0cadnuxxhvkal1mok,1,7,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...",[380],0
3,144g7b7ez101gt3yczm0yblzo,1,18,"12 ({'name': 'Clearance', 'description': 'Play...",81 (???),"6 ({'name': 'Corner Awarded', 'description': '...","[138, 274]",0
4,144g7b7ez101gt3yczm0yblzo,1,47,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"49 ({'name': 'Ball recovery', 'description': '...","[138, 275]",0
5,15au35re7u5b9ru4hoko7f3f8,2,54,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[380],0
6,18ojlro5jtdeu8nv72repur6c,2,76,"61 ({'name': 'Ball touch', 'description': 'Use...",81 (???),"6 ({'name': 'Corner Awarded', 'description': '...","[138, 275]",0
7,1ayj7qyruvkyprfzr6plov4t0,2,50,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...","[138, 275]",0
8,1ayj7qyruvkyprfzr6plov4t0,2,97,"74 ({'name': 'Blocked Pass', 'description': 'D...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...",[380],0
9,1bpdzkqykdmb75z4uarby311w,2,66,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...","[138, 273]",0
10,1dk2hnl09qux7z4fqn1qxq238,1,28,"12 ({'name': 'Clearance', 'description': 'Play...",81 (???),"45 ({'name': 'Challenge', 'description': 'When...",[380],0
11,1eaz7mdny12eiuyeysnycnw2c,2,82,"61 ({'name': 'Ball touch', 'description': 'Use...",81 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[380],0
12,1f9e25njwyjk6ruheatqgglw,1,8,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"27 ({'name': 'Start delay', 'description': 'Us...",[380],0
13,1gkqfp2d7qi9h6k34k3mo8zkk,2,76,"13 ({'name': 'Miss', 'description': 'Any shot ...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...",[380],0
14,1jz2ik6i4oz41zqr2od8yiwb8,1,12,"61 ({'name': 'Ball touch', 'description': 'Use...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...",[380],0
15,1kcl2n7fay0ptltdwj2k47tp0,1,44,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"27 ({'name': 'Start delay', 'description': 'Us...",[380],0
16,1lgsuqoyjxec8b0tdfgdpl15g,2,70,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"27 ({'name': 'Start delay', 'description': 'Us...",[380],0
17,1myp00g7w796yt6ts8ojdkys4,2,72,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[380],0
18,1myp00g7w796yt6ts8ojdkys4,2,81,"1 ({'name': 'Pass', 'description': 'Any pass a...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...",[380],0
19,1nc8632r4hii9bl1ygnappkpg,1,32,"7 ({'name': 'Tackle', 'description': 'Tackle =...",81 (???),"5 ({'name': 'Out', 'description': 'Shown each ...",[380],0

═════════════════════════════════════════════════════════════════
  typeId 83 — ??? (NOT IN MAPPING)   |   5,682 total occurrences
═════════════════════════════════════════════════════════════════

  PREV event (what triggers this event):
     13x   1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
      4x   49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})
      2x   43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})
      1x   83 (???)

  NEXT event (what follows this event):
     13x   1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
      3x   3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})
      2x   61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
      1x   83 (???)
      1x   50 ({'name': 'Dispossessed', 'description': 'Player is successfully tackled and loses possession of the ball'})

  Qualifier IDs on this event (most common first):
     20x   qualifierId 399

  Outcome distribution: {0: 17, 1: 3}

,match,period,minute,prev,target,next,qualifiers,outcome
0,10d1132abu0fa9xolj05top3o,1,2,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"61 ({'name': 'Ball touch', 'description': 'Use...",[399],0
1,10d1132abu0fa9xolj05top3o,1,3,"49 ({'name': 'Ball recovery', 'description': '...",83 (???),83 (???),[399],0
2,10d1132abu0fa9xolj05top3o,1,3,83 (???),83 (???),"61 ({'name': 'Ball touch', 'description': 'Use...",[399],0
3,10d1132abu0fa9xolj05top3o,1,7,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],1
4,10d1132abu0fa9xolj05top3o,1,7,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
5,10d1132abu0fa9xolj05top3o,1,10,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
6,10d1132abu0fa9xolj05top3o,1,19,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
7,10d1132abu0fa9xolj05top3o,1,19,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"3 ({'name': 'Take On', 'description': 'Attempt...",[399],0
8,10d1132abu0fa9xolj05top3o,1,20,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
9,10d1132abu0fa9xolj05top3o,1,35,"43 ({'name': 'Deleted event', 'description': '...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
10,10d1132abu0fa9xolj05top3o,1,45,"49 ({'name': 'Ball recovery', 'description': '...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
11,10d1132abu0fa9xolj05top3o,1,46,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
12,10d1132abu0fa9xolj05top3o,2,50,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"50 ({'name': 'Dispossessed', 'description': 'P...",[399],0
13,10d1132abu0fa9xolj05top3o,2,50,"49 ({'name': 'Ball recovery', 'description': '...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
14,10d1132abu0fa9xolj05top3o,2,57,"49 ({'name': 'Ball recovery', 'description': '...",83 (???),"3 ({'name': 'Take On', 'description': 'Attempt...",[399],0
15,10d1132abu0fa9xolj05top3o,2,66,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"3 ({'name': 'Take On', 'description': 'Attempt...",[399],0
16,10d1132abu0fa9xolj05top3o,2,72,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],1
17,10d1132abu0fa9xolj05top3o,2,81,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
18,10d1132abu0fa9xolj05top3o,2,82,"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],0
19,10d1132abu0fa9xolj05top3o,2,82,"43 ({'name': 'Deleted event', 'description': '...",83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...",[399],1

═════════════════════════════════════════════════════════════════
  typeId 84 — ??? (NOT IN MAPPING)   |   63 total occurrences
═════════════════════════════════════════════════════════════════

  PREV event (what triggers this event):
      7x   4 ({'name': 'Foul', 'description': 'This event is shown when a foul is committed resulting in a free kick'})
      5x   43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})
      3x   55 ({'name': 'Offside provoked', 'description': 'Awarded to last defender when an offside decision is given against an attacker'})
      1x   3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})
      1x   27 ({'name': 'Start delay', 'description': 'Used when there is a stoppage in play such as a player injury'})
      1x   1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
      1x   16 ({'name': 'Goal', 'description': 'All goals'})
      1x   74 ({'name': 'Blocked Pass', 'description': 'Defender is close to player in possession and blocks a pass. Different from interception which is where the player has moved to intercept.'})

  NEXT event (what follows this event):
      8x   27 ({'name': 'Start delay', 'description': 'Used when there is a stoppage in play such as a player injury'})
      5x   43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})
      2x   70 ({'name': 'Injury Time Announcement', 'description': 'Injury Time awarded by Referee'})
      2x   17 ({'name': 'Card', 'description': 'Bookings; will have red, yellow or 2nd yellow qualifier plus a reason'})
      2x   1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
      1x   4 ({'name': 'Foul', 'description': 'This event is shown when a foul is committed resulting in a free kick'})

  Qualifier IDs on this event (most common first):
     20x   qualifierId 436
     20x   qualifierId 343
     16x   qualifierId 56
      9x   qualifierId 103
      9x   qualifierId 102
      8x   qualifierId 55
      8x   qualifierId 231
      8x   qualifierId 230
      7x   qualifierId 375
      7x   qualifierId 374

  Outcome distribution: {1: 18, 0: 2}

,match,period,minute,prev,target,next,qualifiers,outcome
0,10qg7chtpoj0knqnvx2oduot0,2,60,"4 ({'name': 'Foul', 'description': 'This event...",84 (???),"43 ({'name': 'Deleted event', 'description': '...","[56, 436, 343]",1
1,11uxeay5z2isuekqd9fq0usyc,2,89,"43 ({'name': 'Deleted event', 'description': '...",84 (???),"70 ({'name': 'Injury Time Announcement', 'desc...","[343, 152, 56, 295, 436, 286, 13]",0
2,12lophscpllg367yx7yn0mpec,2,66,"43 ({'name': 'Deleted event', 'description': '...",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[375, 55, 133, 29, 214, 103, 56, 20, 78, 231, ...",1
3,12zi2fz6nuyhye00alaymbms4,1,26,"4 ({'name': 'Foul', 'description': 'This event...",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[31, 343, 13, 393, 55, 436]",1
4,14ia91hr21lnjto1f2uga5f6c,1,27,"43 ({'name': 'Deleted event', 'description': '...",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[28, 468, 343, 103, 280, 281, 20, 472, 375, 16...",1
5,14xa2ysiarbslbwcla4hhzqj8,2,90,"55 ({'name': 'Offside provoked', 'description'...",84 (???),"70 ({'name': 'Injury Time Announcement', 'desc...","[374, 72, 154, 328, 436, 24, 343, 55, 230, 29,...",1
6,16fj9cb2vp81vtnlvqdcoou1g,2,52,"55 ({'name': 'Offside provoked', 'description'...",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[15, 56, 231, 230, 214, 436, 16, 343, 154, 25,...",1
7,17xoblao6gdkidisaddnrpa1g,2,46,"4 ({'name': 'Foul', 'description': 'This event...",84 (???),"43 ({'name': 'Deleted event', 'description': '...","[231, 146, 100, 458, 436, 103, 102, 147, 20, 8...",1
8,18b3vyjp3y356x49ce7z1qdxw,2,87,"4 ({'name': 'Foul', 'description': 'This event...",84 (???),"17 ({'name': 'Card', 'description': 'Bookings;...","[392, 13, 31, 55, 436, 343]",1
9,19ubgm1lxlw64hrajkv1cc5ck,2,66,"43 ({'name': 'Deleted event', 'description': '...",84 (???),"43 ({'name': 'Deleted event', 'description': '...","[214, 458, 80, 17, 147, 9, 56, 436, 72, 146, 3...",1
10,1a7radhhole7vfnciarzauq6s,2,51,"4 ({'name': 'Foul', 'description': 'This event...",84 (???),"43 ({'name': 'Deleted event', 'description': '...","[343, 55, 31, 13, 392, 436]",1
11,1a7radhhole7vfnciarzauq6s,2,89,"3 ({'name': 'Take On', 'description': 'Attempt...",84 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...","[140, 141, 7, 343, 436, 8, 56]",1
12,1ayj7qyruvkyprfzr6plov4t0,2,62,"43 ({'name': 'Deleted event', 'description': '...",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[328, 16, 436, 458, 25, 214, 76, 375, 343, 20,...",1
13,1bbwtdnimi7tbl6aatezlnwno,2,74,"27 ({'name': 'Start delay', 'description': 'Us...",84 (???),"43 ({'name': 'Deleted event', 'description': '...","[13, 152, 436, 286, 343, 56, 9, 233, 265]",1
14,1bbwtdnimi7tbl6aatezlnwno,2,82,"1 ({'name': 'Pass', 'description': 'Any pass a...",84 (???),"1 ({'name': 'Pass', 'description': 'Any pass a...","[436, 1, 140, 56, 343, 7, 141]",1
15,1c2s2pxxqc6pp652crmn64etw,1,39,"4 ({'name': 'Foul', 'description': 'This event...",84 (???),"17 ({'name': 'Card', 'description': 'Bookings;...","[230, 56, 16, 343, 231, 214, 375, 22, 102, 103...",1
16,1cg5aiu7phyw89gyr0m9hme50,2,91,"16 ({'name': 'Goal', 'description': 'All goals'})",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[436, 141, 56, 8, 7, 140, 343]",1
17,1g7ev92a4xzvmnte18e1h7thw,2,81,"55 ({'name': 'Offside provoked', 'description'...",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[20, 56, 230, 22, 18, 78, 120, 343, 214, 231, ...",1
18,1i2f9ycdq0mof2nmr7jievlsk,2,87,"4 ({'name': 'Foul', 'description': 'This event...",84 (???),"27 ({'name': 'Start delay', 'description': 'Us...","[343, 13, 436, 31, 392, 55]",1
19,1jz2ik6i4oz41zqr2od8yiwb8,2,61,"74 ({'name': 'Blocked Pass', 'description': 'D...",84 (???),"4 ({'name': 'Foul', 'description': 'This event...","[56, 343, 436]",0

In [19]:
# ── Which event typeIds use qualifierId 265? ────────────────────────────────

TARGET_QUALIFIER = 265
MAX_SAMPLES      = 1

samples_q265 = []

for fp in sorted(all_files):
    if len(samples_q265) >= MAX_SAMPLES:
        break
    try:
        data   = extract_json_from_jsonp(fp)
        events = data["liveData"]["event"]
    except Exception:
        continue

    for ev in events:
        for q in ev.get("qualifier", []):
            if q.get("qualifierId") == TARGET_QUALIFIER:
                samples_q265.append({
                    "match"    : fp.name,
                    "period"   : ev.get("periodId"),
                    "minute"   : ev.get("timeMin"),
                    "typeId"   : ev.get("typeId"),
                    "event"    : label(ev.get("typeId"), events_mapping),
                    "q265_val" : q.get("value"),
                    "outcome"  : ev.get("outcome"),
                })
        if len(samples_q265) >= MAX_SAMPLES:
            break

# ── Summary ──────────────────────────────────────────────────────────────────
from collections import Counter

type_counts = Counter(s["typeId"] for s in samples_q265)
print(f"qualifierId {TARGET_QUALIFIER} found on {len(samples_q265)} sampled events\n")
print("Event typeIds that carry this qualifier:")
for tid, cnt in type_counts.most_common():
    print(f"  {cnt:>3}x   {label(tid, events_mapping)}")

print()
display(pd.DataFrame(samples_q265))

qualifierId 265 found on 1 sampled events

Event typeIds that carry this qualifier:
    1x   4 ({'name': 'Foul', 'description': 'This event is shown when a foul is committed resulting in a free kick'})

,match,period,minute,typeId,event,q265_val,outcome
0,10d1132abu0fa9xolj05top3o,1,6,4,"4 ({'name': 'Foul', 'description': 'This event...",None,1

In [21]:
# ── typeId 83 (Attempted Tackle) — possession-flow analysis ─────────────────
#
# For each occurrence we look at the event immediately before and after (same
# period). We then classify into 4 categories based on which team owns those
# surrounding events vs which team performed the attempted tackle.
#
# Conventions:
#   "OPP has ball"  → surrounding event belongs to the OTHER team (opponent
#                     is in possession, the typeId-83 player is defending)
#   "OWN has ball"  → surrounding event belongs to the SAME team as the
#                     typeId-83 player (own team in possession — edge case)
#
# Categories:
#   1. OPP → [83] → OPP   opponent keeps the ball (tackle attempt failed)
#   2. OPP → [83] → OWN   own team wins the ball  (tackle attempt succeeded)
#   3. OWN → [83] → OPP   own team loses the ball (very unusual)
#   4. OWN → [83] → OWN   own team keeps the ball (very unusual)

from collections import defaultdict, Counter

TARGET_TYPE_ID  = 83
SAMPLES_PER_CAT = 30   # max raw examples stored per category

# ── Storage ──────────────────────────────────────────────────────────────────
category_counts = Counter()
category_prev_events = defaultdict(Counter)   # cat → Counter of prev event labels
category_next_events = defaultdict(Counter)   # cat → Counter of next event labels
category_samples     = defaultdict(list)      # cat → list of example rows


def possession_side(event, actor_team_id):
    """
    Returns 'OWN' if the event's contestantId matches actor_team_id,
    'OPP' otherwise. Returns None if contestantId is missing.
    """
    eid = event.get("contestantId")
    if eid is None:
        return None
    return "OWN" if eid == actor_team_id else "OPP"


def classify(prev_side, next_side):
    if prev_side == "OPP" and next_side == "OPP":
        return "1. OPP→[83]→OPP  (opponent keeps ball)"
    if prev_side == "OPP" and next_side == "OWN":
        return "2. OPP→[83]→OWN  (own team wins ball)"
    if prev_side == "OWN" and next_side == "OPP":
        return "3. OWN→[83]→OPP  (own team loses ball)"
    if prev_side == "OWN" and next_side == "OWN":
        return "4. OWN→[83]→OWN  (own team keeps ball)"
    return "5. UNKNOWN (missing contestantId on neighbour)"


# ── Scan all match files ──────────────────────────────────────────────────────
for fp in sorted(all_files):
    try:
        data   = extract_json_from_jsonp(fp)
        events = data["liveData"]["event"]
    except Exception:
        continue

    # Group by period to avoid half-time bleed
    by_period = defaultdict(list)
    for ev in events:
        by_period[ev.get("periodId", 0)].append(ev)

    for period_id, pevents in by_period.items():
        for i, ev in enumerate(pevents):
            if ev.get("typeId") != TARGET_TYPE_ID:
                continue

            actor_team = ev.get("contestantId")
            if actor_team is None:
                continue

            prev_ev = pevents[i - 1] if i > 0 else None
            next_ev = pevents[i + 1] if i < len(pevents) - 1 else None

            prev_side = possession_side(prev_ev, actor_team) if prev_ev else None
            next_side = possession_side(next_ev, actor_team) if next_ev else None

            if prev_side is None or next_side is None:
                continue   # skip boundary events with no neighbour

            cat = classify(prev_side, next_side)
            category_counts[cat] += 1

            prev_label = label(prev_ev.get("typeId"), events_mapping)
            next_label = label(next_ev.get("typeId"), events_mapping)
            category_prev_events[cat][prev_label] += 1
            category_next_events[cat][next_label] += 1

            if len(category_samples[cat]) < SAMPLES_PER_CAT:
                category_samples[cat].append({
                    "match"      : fp.name,
                    "period"     : period_id,
                    "minute"     : ev.get("timeMin"),
                    "prev_event" : prev_label,
                    "prev_team"  : prev_side,
                    "outcome_83" : ev.get("outcome"),
                    "next_event" : next_label,
                    "next_team"  : next_side,
                })


# ── Print results ─────────────────────────────────────────────────────────────
total = sum(category_counts.values())
print(f"typeId {TARGET_TYPE_ID} — Attempted Tackle")
print(f"Total classified events: {total:,}\n")

for cat in sorted(category_counts):
    cnt  = category_counts[cat]
    pct  = cnt / total * 100
    print("=" * 65)
    print(f"  {cat}")
    print(f"  Count: {cnt:,}  ({pct:.1f}%)")

    print("\n  Most common PREV events:")
    for ev_label, c in category_prev_events[cat].most_common(5):
        print(f"    {c:>4}x  {ev_label}")

    print("\n  Most common NEXT events:")
    for ev_label, c in category_next_events[cat].most_common(5):
        print(f"    {c:>4}x  {ev_label}")

    print(f"\n  Sample rows (up to {SAMPLES_PER_CAT}):")
    display(pd.DataFrame(category_samples[cat]))

typeId 83 — Attempted Tackle
Total classified events: 5,682

=================================================================
  1. OPP→[83]→OPP  (opponent keeps ball)
  Count: 4,043  (71.2%)

  Most common PREV events:
    3047x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
     516x  49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})
     117x  3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})
      91x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
      86x  43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})

  Most common NEXT events:
    2399x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
     560x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
     358x  3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})
     275x  50 ({'name': 'Dispossessed', 'description': 'Player is successfully tackled and loses possession of the ball'})
     162x  49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})

  Sample rows (up to 30):

,match,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,10d1132abu0fa9xolj05top3o,1,2,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
1,10d1132abu0fa9xolj05top3o,1,7,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,1,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
2,10d1132abu0fa9xolj05top3o,1,7,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
3,10d1132abu0fa9xolj05top3o,1,10,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
4,10d1132abu0fa9xolj05top3o,1,19,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
5,10d1132abu0fa9xolj05top3o,1,19,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"3 ({'name': 'Take On', 'description': 'Attempt...",OPP
6,10d1132abu0fa9xolj05top3o,1,20,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
7,10d1132abu0fa9xolj05top3o,1,45,"49 ({'name': 'Ball recovery', 'description': '...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
8,10d1132abu0fa9xolj05top3o,1,46,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
9,10d1132abu0fa9xolj05top3o,2,50,"49 ({'name': 'Ball recovery', 'description': '...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
10,10d1132abu0fa9xolj05top3o,2,57,"49 ({'name': 'Ball recovery', 'description': '...",OPP,0,"3 ({'name': 'Take On', 'description': 'Attempt...",OPP
11,10d1132abu0fa9xolj05top3o,2,66,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"3 ({'name': 'Take On', 'description': 'Attempt...",OPP
12,10d1132abu0fa9xolj05top3o,2,72,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,1,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
13,10d1132abu0fa9xolj05top3o,2,81,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
14,10d1132abu0fa9xolj05top3o,2,82,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
15,10d1132abu0fa9xolj05top3o,2,84,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
16,10d1132abu0fa9xolj05top3o,2,87,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"4 ({'name': 'Foul', 'description': 'This event...",OPP
17,10qg7chtpoj0knqnvx2oduot0,1,1,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
18,10qg7chtpoj0knqnvx2oduot0,1,8,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
19,10qg7chtpoj0knqnvx2oduot0,1,25,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
20,10qg7chtpoj0knqnvx2oduot0,1,27,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
21,10qg7chtpoj0knqnvx2oduot0,1,28,"49 ({'name': 'Ball recovery', 'description': '...",OPP,0,"50 ({'name': 'Dispossessed', 'description': 'P...",OPP
22,10qg7chtpoj0knqnvx2oduot0,1,28,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,1,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
23,10qg7chtpoj0knqnvx2oduot0,1,33,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
24,10qg7chtpoj0knqnvx2oduot0,1,45,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"50 ({'name': 'Dispossessed', 'description': 'P...",OPP
25,10qg7chtpoj0knqnvx2oduot0,1,45,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,1,"13 ({'name': 'Miss', 'description': 'Any shot ...",OPP
26,10qg7chtpoj0knqnvx2oduot0,2,50,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
27,10qg7chtpoj0knqnvx2oduot0,2,55,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
28,10qg7chtpoj0knqnvx2oduot0,2,57,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
29,10qg7chtpoj0knqnvx2oduot0,2,66,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OPP

=================================================================
  2. OPP→[83]→OWN  (own team wins ball)
  Count: 432  (7.6%)

  Most common PREV events:
     307x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
      68x  49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})
      23x  3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})
      12x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
       9x  7 ({'name': 'Tackle', 'description': 'Tackle = dispossesses an opponent of the ball - Outcome 1 = win & retain possession or out of play, 0 = win tackle but not possession'})

  Most common NEXT events:
     293x  83 (???)
      70x  43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})
      68x  45 ({'name': 'Challenge', 'description': 'When a player fails to win the ball as an opponent successfully dribbles past them'})
       1x  70 ({'name': 'Injury Time Announcement', 'description': 'Injury Time awarded by Referee'})

  Sample rows (up to 30):

,match,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,10d1132abu0fa9xolj05top3o,1,3,"49 ({'name': 'Ball recovery', 'description': '...",OPP,0,83 (???),OWN
1,10d1132abu0fa9xolj05top3o,2,90,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,1,"43 ({'name': 'Deleted event', 'description': '...",OWN
2,10qg7chtpoj0knqnvx2oduot0,1,21,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
3,10qg7chtpoj0knqnvx2oduot0,2,53,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
4,10qg7chtpoj0knqnvx2oduot0,2,59,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
5,11hplskmrac4dwfmqv72f9nh0,1,14,"8 ({'name': 'Interception', 'description': 'Wh...",OPP,1,"43 ({'name': 'Deleted event', 'description': '...",OWN
6,11uxeay5z2isuekqd9fq0usyc,1,16,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
7,11uxeay5z2isuekqd9fq0usyc,2,66,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
8,1288ajju0cadnuxxhvkal1mok,1,32,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
9,1288ajju0cadnuxxhvkal1mok,2,84,"49 ({'name': 'Ball recovery', 'description': '...",OPP,1,"43 ({'name': 'Deleted event', 'description': '...",OWN
10,12lophscpllg367yx7yn0mpec,1,3,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
11,12lophscpllg367yx7yn0mpec,1,17,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
12,12lophscpllg367yx7yn0mpec,1,28,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
13,12zi2fz6nuyhye00alaymbms4,1,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
14,13d50vdn5ecuddcpg1cvdrq50,2,49,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
15,13d50vdn5ecuddcpg1cvdrq50,2,61,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
16,13qwzalezgy8gxih0ube0ap78,1,5,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
17,13qwzalezgy8gxih0ube0ap78,1,41,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
18,13qwzalezgy8gxih0ube0ap78,1,42,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
19,144g7b7ez101gt3yczm0yblzo,1,27,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
20,144g7b7ez101gt3yczm0yblzo,2,76,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
21,14ia91hr21lnjto1f2uga5f6c,1,24,"3 ({'name': 'Take On', 'description': 'Attempt...",OPP,1,"45 ({'name': 'Challenge', 'description': 'When...",OWN
22,14ia91hr21lnjto1f2uga5f6c,1,46,"49 ({'name': 'Ball recovery', 'description': '...",OPP,0,83 (???),OWN
23,14ia91hr21lnjto1f2uga5f6c,2,69,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN
24,14xa2ysiarbslbwcla4hhzqj8,1,16,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
25,14xa2ysiarbslbwcla4hhzqj8,2,87,"49 ({'name': 'Ball recovery', 'description': '...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
26,15au35re7u5b9ru4hoko7f3f8,1,13,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
27,15au35re7u5b9ru4hoko7f3f8,1,20,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
28,15au35re7u5b9ru4hoko7f3f8,1,33,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
29,15au35re7u5b9ru4hoko7f3f8,1,42,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP,0,83 (???),OWN

=================================================================
  3. OWN→[83]→OPP  (own team loses ball)
  Count: 1,092  (19.2%)

  Most common PREV events:
     329x  83 (???)
     203x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
     140x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
     112x  7 ({'name': 'Tackle', 'description': 'Tackle = dispossesses an opponent of the ball - Outcome 1 = win & retain possession or out of play, 0 = win tackle but not possession'})
      84x  12 ({'name': 'Clearance', 'description': 'Player under pressure hits the ball clear of the defensive zone or/and out of play'})

  Most common NEXT events:
     487x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
     209x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
     119x  49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})
     105x  3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})
      82x  50 ({'name': 'Dispossessed', 'description': 'Player is successfully tackled and loses possession of the ball'})

  Sample rows (up to 30):

,match,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,10d1132abu0fa9xolj05top3o,1,3,83 (???),OWN,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
1,10d1132abu0fa9xolj05top3o,1,35,"43 ({'name': 'Deleted event', 'description': '...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
2,10d1132abu0fa9xolj05top3o,2,50,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,0,"50 ({'name': 'Dispossessed', 'description': 'P...",OPP
3,10d1132abu0fa9xolj05top3o,2,82,"43 ({'name': 'Deleted event', 'description': '...",OWN,1,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
4,10qg7chtpoj0knqnvx2oduot0,1,7,"12 ({'name': 'Clearance', 'description': 'Play...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
5,10qg7chtpoj0knqnvx2oduot0,1,21,83 (???),OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
6,10qg7chtpoj0knqnvx2oduot0,1,35,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
7,10qg7chtpoj0knqnvx2oduot0,2,48,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
8,10qg7chtpoj0knqnvx2oduot0,2,53,83 (???),OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
9,10qg7chtpoj0knqnvx2oduot0,2,54,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,1,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
10,113wccwt50kebz0thqf0fxkpg,1,44,"12 ({'name': 'Clearance', 'description': 'Play...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
11,113wccwt50kebz0thqf0fxkpg,2,53,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,0,"49 ({'name': 'Ball recovery', 'description': '...",OPP
12,113wccwt50kebz0thqf0fxkpg,2,82,"7 ({'name': 'Tackle', 'description': 'Tackle =...",OWN,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
13,113wccwt50kebz0thqf0fxkpg,2,82,"45 ({'name': 'Challenge', 'description': 'When...",OWN,0,"50 ({'name': 'Dispossessed', 'description': 'P...",OPP
14,113wccwt50kebz0thqf0fxkpg,2,91,83 (???),OWN,1,"3 ({'name': 'Take On', 'description': 'Attempt...",OPP
15,11hplskmrac4dwfmqv72f9nh0,1,40,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
16,11hplskmrac4dwfmqv72f9nh0,2,62,"45 ({'name': 'Challenge', 'description': 'When...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
17,11hplskmrac4dwfmqv72f9nh0,2,79,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
18,11uxeay5z2isuekqd9fq0usyc,1,5,"43 ({'name': 'Deleted event', 'description': '...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
19,11uxeay5z2isuekqd9fq0usyc,1,25,"43 ({'name': 'Deleted event', 'description': '...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
20,11uxeay5z2isuekqd9fq0usyc,1,26,"7 ({'name': 'Tackle', 'description': 'Tackle =...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
21,11uxeay5z2isuekqd9fq0usyc,2,66,83 (???),OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
22,1288ajju0cadnuxxhvkal1mok,1,28,"43 ({'name': 'Deleted event', 'description': '...",OWN,0,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
23,1288ajju0cadnuxxhvkal1mok,1,29,"45 ({'name': 'Challenge', 'description': 'When...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
24,1288ajju0cadnuxxhvkal1mok,1,32,83 (???),OWN,0,"50 ({'name': 'Dispossessed', 'description': 'P...",OPP
25,1288ajju0cadnuxxhvkal1mok,2,78,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,1,"61 ({'name': 'Ball touch', 'description': 'Use...",OPP
26,1288ajju0cadnuxxhvkal1mok,2,80,"45 ({'name': 'Challenge', 'description': 'When...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
27,12lophscpllg367yx7yn0mpec,1,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,0,"50 ({'name': 'Dispossessed', 'description': 'P...",OPP
28,12lophscpllg367yx7yn0mpec,1,9,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,0,"1 ({'name': 'Pass', 'description': 'Any pass a...",OPP
29,12lophscpllg367yx7yn0mpec,1,27,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,0,"49 ({'name': 'Ball recovery', 'description': '...",OPP

=================================================================
  4. OWN→[83]→OWN  (own team keeps ball)
  Count: 115  (2.0%)

  Most common PREV events:
      39x  83 (???)
      19x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})
      17x  7 ({'name': 'Tackle', 'description': 'Tackle = dispossesses an opponent of the ball - Outcome 1 = win & retain possession or out of play, 0 = win tackle but not possession'})
      12x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})
       7x  43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})

  Most common NEXT events:
      75x  83 (???)
      21x  45 ({'name': 'Challenge', 'description': 'When a player fails to win the ball as an opponent successfully dribbles past them'})
      19x  43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})

  Sample rows (up to 30):

,match,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,113wccwt50kebz0thqf0fxkpg,2,91,"74 ({'name': 'Blocked Pass', 'description': 'D...",OWN,0,83 (???),OWN
1,113wccwt50kebz0thqf0fxkpg,2,91,83 (???),OWN,0,83 (???),OWN
2,1288ajju0cadnuxxhvkal1mok,1,24,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,1,"43 ({'name': 'Deleted event', 'description': '...",OWN
3,12lophscpllg367yx7yn0mpec,1,3,83 (???),OWN,0,"43 ({'name': 'Deleted event', 'description': '...",OWN
4,12lophscpllg367yx7yn0mpec,2,59,"12 ({'name': 'Clearance', 'description': 'Play...",OWN,0,83 (???),OWN
5,13d50vdn5ecuddcpg1cvdrq50,1,18,"43 ({'name': 'Deleted event', 'description': '...",OWN,0,83 (???),OWN
6,13qwzalezgy8gxih0ube0ap78,2,83,"40 ({'name': 'Formation change', 'description'...",OWN,0,83 (???),OWN
7,144g7b7ez101gt3yczm0yblzo,1,27,83 (???),OWN,0,83 (???),OWN
8,144g7b7ez101gt3yczm0yblzo,2,52,"7 ({'name': 'Tackle', 'description': 'Tackle =...",OWN,0,83 (???),OWN
9,144g7b7ez101gt3yczm0yblzo,2,57,"7 ({'name': 'Tackle', 'description': 'Tackle =...",OWN,0,83 (???),OWN
10,16234pc0mx6bpyeqhj4i81p90,2,58,"12 ({'name': 'Clearance', 'description': 'Play...",OWN,0,83 (???),OWN
11,176p8ms7mmtnsyiwqb87aavx0,1,22,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
12,18ojlro5jtdeu8nv72repur6c,1,11,83 (???),OWN,0,83 (???),OWN
13,18ojlro5jtdeu8nv72repur6c,1,11,83 (???),OWN,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
14,1a7radhhole7vfnciarzauq6s,2,89,83 (???),OWN,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
15,1al4jq2l4mkefxzf7iqmiledw,2,56,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,0,83 (???),OWN
16,1ayj7qyruvkyprfzr6plov4t0,1,34,"7 ({'name': 'Tackle', 'description': 'Tackle =...",OWN,0,83 (???),OWN
17,1bbwtdnimi7tbl6aatezlnwno,2,80,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
18,1bpdzkqykdmb75z4uarby311w,2,94,83 (???),OWN,0,83 (???),OWN
19,1c2s2pxxqc6pp652crmn64etw,1,38,"43 ({'name': 'Deleted event', 'description': '...",OWN,0,83 (???),OWN
20,1cg5aiu7phyw89gyr0m9hme50,1,21,83 (???),OWN,0,83 (???),OWN
21,1ctejm87t066zop4ert2zb4es,2,94,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,1,"45 ({'name': 'Challenge', 'description': 'When...",OWN
22,1d6oxum3q5ydyzsf48df1qas4,1,39,83 (???),OWN,0,83 (???),OWN
23,1dxl0z31i0438ti5nrd22dl3o,1,22,"61 ({'name': 'Ball touch', 'description': 'Use...",OWN,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
24,1dxl0z31i0438ti5nrd22dl3o,2,80,"7 ({'name': 'Tackle', 'description': 'Tackle =...",OWN,0,83 (???),OWN
25,1eq00zu9dngz36evkyw20uw44,1,12,"1 ({'name': 'Pass', 'description': 'Any pass a...",OWN,0,"45 ({'name': 'Challenge', 'description': 'When...",OWN
26,1f3hreqlw5s8sg03041v1ecyc,1,21,"45 ({'name': 'Challenge', 'description': 'When...",OWN,0,83 (???),OWN
27,1f9e25njwyjk6ruheatqgglw,2,96,83 (???),OWN,0,83 (???),OWN
28,1gkqfp2d7qi9h6k34k3mo8zkk,1,1,"7 ({'name': 'Tackle', 'description': 'Tackle =...",OWN,0,83 (???),OWN
29,1i2f9ycdq0mof2nmr7jievlsk,1,1,83 (???),OWN,0,83 (???),OWN

In [3]:
# %% [markdown]
# # Attempted Tackle (typeId 83) — Possession-Flow Analysis
#
# For each attempted tackle we look at the event immediately before and
# after (same match + period) and classify into 4 categories:
#
# 1. **OPP → [83] → OPP** — opponent keeps the ball (tackle failed)
# 2. **OPP → [83] → OWN** — own team wins the ball (tackle succeeded)
# 3. **OWN → [83] → OPP** — own team loses the ball (unusual)
# 4. **OWN → [83] → OWN** — own team keeps the ball (unusual)

# %% ── Config ────────────────────────────────────────────────────────────────

TARGET_TYPE_ID  = 83
SAMPLES_PER_CAT = 30

# Optional: restrict to specific matches (set to None for all matches)
MATCH_IDS = None   # e.g. [101, 102, 103]

# %% ── Imports & connection ──────────────────────────────────────────────────

from collections import Counter, defaultdict
import pandas as pd
import psycopg2

FOOTBALL_DB_DSN='postgresql://postgres:WuLei2422@localhost:5432/football_analytics'

conn = psycopg2.connect(FOOTBALL_DB_DSN)   # adjust DSN as needed

# %% ── Query ─────────────────────────────────────────────────────────────────

sql = """
WITH ordered AS (
    SELECT
        event_id,
        match_id,
        period,
        minute,
        second,
        type_id,
        event_type,
        outcome,
        team_id,

        LAG(team_id)     OVER w AS prev_team_id,
        LAG(event_type)  OVER w AS prev_event_type,

        LEAD(team_id)    OVER w AS next_team_id,
        LEAD(event_type) OVER w AS next_event_type
    FROM silver.events
    WHERE period NOT IN (14, 16)
      AND event_type NOT IN ('FormationChange', 'FormationSet')
    WINDOW w AS (
        PARTITION BY match_id, period
        ORDER BY minute, second, event_id
    )
)
SELECT *
FROM ordered
WHERE type_id = %(target_type_id)s
  AND prev_team_id IS NOT NULL
  AND next_team_id IS NOT NULL
"""

params = {"target_type_id": TARGET_TYPE_ID}

if MATCH_IDS is not None:
    sql += "  AND match_id = ANY(%(match_ids)s)"
    params["match_ids"] = MATCH_IDS

df = pd.read_sql(sql, conn, params=params)
print(f"Rows fetched: {len(df):,}")

# %% ── Classify ──────────────────────────────────────────────────────────────

def _side(neighbour_team_id, actor_team_id):
    return "OWN" if neighbour_team_id == actor_team_id else "OPP"

_LABELS = {
    ("OPP", "OPP"): "1. OPP→[83]→OPP  (opponent keeps ball)",
    ("OPP", "OWN"): "2. OPP→[83]→OWN  (own team wins ball)",
    ("OWN", "OPP"): "3. OWN→[83]→OPP  (own team loses ball)",
    ("OWN", "OWN"): "4. OWN→[83]→OWN  (own team keeps ball)",
}

category_counts = Counter()
category_prev   = defaultdict(Counter)
category_next   = defaultdict(Counter)
category_samples = defaultdict(list)

for row in df.itertuples(index=False):
    prev_side = _side(row.prev_team_id, row.team_id)
    next_side = _side(row.next_team_id, row.team_id)
    cat = _LABELS.get((prev_side, next_side), "5. UNKNOWN")

    category_counts[cat] += 1
    category_prev[cat][row.prev_event_type] += 1
    category_next[cat][row.next_event_type] += 1

    if len(category_samples[cat]) < SAMPLES_PER_CAT:
        category_samples[cat].append({
            "match_id":   row.match_id,
            "period":     row.period,
            "minute":     row.minute,
            "prev_event": row.prev_event_type,
            "prev_team":  prev_side,
            "outcome_83": row.outcome,
            "next_event": row.next_event_type,
            "next_team":  next_side,
        })

# %% ── Results ───────────────────────────────────────────────────────────────

total = sum(category_counts.values())
print(f"typeId {TARGET_TYPE_ID} — Attempted Tackle")
print(f"Total classified events: {total:,}\n")

for cat in sorted(category_counts):
    cnt = category_counts[cat]
    pct = cnt / total * 100 if total else 0

    print("=" * 65)
    print(f"  {cat}")
    print(f"  Count: {cnt:,}  ({pct:.1f}%)")

    print("\n  Most common PREV events:")
    for ev_label, c in category_prev[cat].most_common(5):
        print(f"    {c:>4}x  {ev_label}")

    print("\n  Most common NEXT events:")
    for ev_label, c in category_next[cat].most_common(5):
        print(f"    {c:>4}x  {ev_label}")

    print()

# %% ── Sample rows per category ─────────────────────────────────────────────

for cat in sorted(category_samples):
    print(f"\n{cat}")
    display(pd.DataFrame(category_samples[cat]))

C:\Users\Usuario\AppData\Local\Temp\ipykernel_33880\3049540509.py:71: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, conn, params=params)

Rows fetched: 6,768
typeId 83 — Attempted Tackle
Total classified events: 6,768

=================================================================
  1. OPP→[83]→OPP  (opponent keeps ball)
  Count: 4,894  (72.3%)

  Most common PREV events:
    3688x  Pass
     671x  Ball recovery
     144x  Take On
     123x  Ball touch
      94x  Tackle

  Most common NEXT events:
    2958x  Pass
     688x  Ball touch
     432x  Take On
     332x  Dispossessed
     221x  Foul

=================================================================
  2. OPP→[83]→OWN  (own team wins ball)
  Count: 459  (6.8%)

  Most common PREV events:
     336x  Pass
      71x  Ball recovery
      24x  Take On
      11x  Ball touch
       6x  Tackle

  Most common NEXT events:
     360x  Attempted Tackle
      72x  Challenge
      25x  Carry
       1x  Start delay
       1x  Injury Time Announcement

=================================================================
  3. OWN→[83]→OPP  (own team loses ball)
  Count: 1,291  (19.1%)

  Most common PREV events:
     397x  Attempted Tackle
     248x  Ball touch
     176x  Pass
     143x  Tackle
     106x  Clearance

  Most common NEXT events:
     594x  Pass
     257x  Ball touch
     131x  Ball recovery
     127x  Take On
      90x  Dispossessed

=================================================================
  4. OWN→[83]→OWN  (own team keeps ball)
  Count: 124  (1.8%)

  Most common PREV events:
      52x  Attempted Tackle
      20x  Ball touch
      17x  Tackle
       9x  Pass
       8x  Clearance

  Most common NEXT events:
      89x  Attempted Tackle
      30x  Challenge
       3x  Carry
       1x  End
       1x  Foul


1. OPP→[83]→OPP  (opponent keeps ball)

,match_id,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,1,1,2,Pass,OPP,failure,Ball touch,OPP
1,1,1,7,Pass,OPP,failure,Pass,OPP
2,1,1,7,Pass,OPP,failure,Pass,OPP
3,1,1,10,Pass,OPP,failure,Pass,OPP
4,1,1,19,Pass,OPP,failure,Pass,OPP
5,1,1,19,Pass,OPP,failure,Take On,OPP
6,1,1,20,Pass,OPP,failure,Pass,OPP
7,1,1,35,Ball recovery,OPP,failure,Pass,OPP
8,1,1,45,Ball recovery,OPP,failure,Pass,OPP
9,1,1,46,Pass,OPP,failure,Pass,OPP
10,1,2,50,Ball recovery,OPP,failure,Pass,OPP
11,1,2,57,Ball recovery,OPP,failure,Take On,OPP
12,1,2,66,Pass,OPP,failure,Take On,OPP
13,1,2,72,Pass,OPP,failure,Pass,OPP
14,1,2,81,Pass,OPP,failure,Pass,OPP
15,1,2,82,Pass,OPP,failure,Pass,OPP
16,1,2,82,Ball touch,OPP,failure,Pass,OPP
17,1,2,84,Pass,OPP,failure,Pass,OPP
18,1,2,87,Pass,OPP,failure,Foul,OPP
19,1,2,90,Pass,OPP,failure,Pass,OPP
20,2,1,2,Pass,OPP,failure,Take On,OPP
21,2,1,21,Pass,OPP,failure,Pass,OPP
22,2,1,27,Pass,OPP,failure,Pass,OPP
23,2,1,37,Pass,OPP,failure,Pass,OPP
24,2,2,49,Tackle,OPP,failure,Foul,OPP
25,2,2,50,Pass,OPP,failure,Pass,OPP
26,2,2,50,Take On,OPP,failure,Pass,OPP
27,2,2,57,Pass,OPP,failure,Take On,OPP
28,2,2,58,Pass,OPP,failure,Pass,OPP
29,2,2,58,Pass,OPP,failure,Pass,OPP

2. OPP→[83]→OWN  (own team wins ball)

,match_id,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,1,1,3,Ball recovery,OPP,failure,Attempted Tackle,OWN
1,2,2,47,Pass,OPP,failure,Carry,OWN
2,3,1,2,Pass,OPP,failure,Start delay,OWN
3,3,1,14,Pass,OPP,failure,Attempted Tackle,OWN
4,3,1,28,Pass,OPP,failure,Attempted Tackle,OWN
5,3,1,35,Pass,OPP,failure,Attempted Tackle,OWN
6,3,2,96,Pass,OPP,failure,Attempted Tackle,OWN
7,4,1,21,Pass,OPP,failure,Attempted Tackle,OWN
8,5,1,43,Ball recovery,OPP,failure,Attempted Tackle,OWN
9,6,1,13,Ball recovery,OPP,failure,Attempted Tackle,OWN
10,6,2,53,Pass,OPP,failure,Attempted Tackle,OWN
11,7,1,6,Pass,OPP,failure,Attempted Tackle,OWN
12,7,1,21,Ball recovery,OPP,failure,Attempted Tackle,OWN
13,7,2,81,Ball recovery,OPP,failure,Attempted Tackle,OWN
14,8,1,3,Pass,OPP,failure,Attempted Tackle,OWN
15,8,1,9,Ball recovery,OPP,failure,Attempted Tackle,OWN
16,8,1,49,Pass,OPP,failure,Attempted Tackle,OWN
17,9,1,31,Pass,OPP,failure,Attempted Tackle,OWN
18,9,1,45,Ball recovery,OPP,failure,Attempted Tackle,OWN
19,9,2,90,Pass,OPP,failure,Attempted Tackle,OWN
20,10,1,28,Pass,OPP,failure,Attempted Tackle,OWN
21,10,1,40,Take On,OPP,failure,Attempted Tackle,OWN
22,10,2,92,Pass,OPP,failure,Carry,OWN
23,11,2,84,Pass,OPP,failure,Challenge,OWN
24,12,1,22,Ball recovery,OPP,failure,Attempted Tackle,OWN
25,12,1,29,Pass,OPP,failure,Attempted Tackle,OWN
26,13,1,3,Pass,OPP,failure,Attempted Tackle,OWN
27,13,1,31,Pass,OPP,failure,Challenge,OWN
28,14,1,35,Ball recovery,OPP,failure,Attempted Tackle,OWN
29,15,2,78,Pass,OPP,failure,Attempted Tackle,OWN

3. OWN→[83]→OPP  (own team loses ball)

,match_id,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,1,1,3,Attempted Tackle,OWN,failure,Ball touch,OPP
1,1,2,50,Pass,OWN,failure,Dispossessed,OPP
2,2,1,3,Pass,OWN,failure,Ball recovery,OPP
3,2,1,3,Pass,OWN,failure,Dispossessed,OPP
4,2,1,32,Tackle,OWN,failure,Pass,OPP
5,3,1,14,Attempted Tackle,OWN,failure,Pass,OPP
6,3,1,28,Attempted Tackle,OWN,failure,Take On,OPP
7,3,1,35,Attempted Tackle,OWN,failure,Ball touch,OPP
8,3,2,56,Ball touch,OWN,failure,Take On,OPP
9,3,2,59,Interception,OWN,failure,Pass,OPP
10,3,2,67,Pass,OWN,failure,Ball touch,OPP
11,3,2,88,Aerial,OWN,failure,Ball touch,OPP
12,3,2,96,Attempted Tackle,OWN,failure,Foul,OPP
13,4,1,21,Attempted Tackle,OWN,failure,Ball touch,OPP
14,4,1,41,Challenge,OWN,failure,Take On,OPP
15,4,1,42,Ball touch,OWN,failure,Pass,OPP
16,4,2,77,Ball touch,OWN,failure,Ball recovery,OPP
17,4,2,95,Pass,OWN,failure,Ball recovery,OPP
18,5,1,43,Attempted Tackle,OWN,failure,Pass,OPP
19,6,1,13,Attempted Tackle,OWN,failure,Pass,OPP
20,6,2,53,Attempted Tackle,OWN,failure,Pass,OPP
21,6,2,84,Blocked Pass,OWN,failure,Ball recovery,OPP
22,7,1,5,Tackle,OWN,failure,Pass,OPP
23,7,1,6,Attempted Tackle,OWN,failure,Ball touch,OPP
24,7,1,10,Pass,OWN,failure,Pass,OPP
25,7,1,21,Attempted Tackle,OWN,failure,Pass,OPP
26,7,1,42,Pass,OWN,failure,Ball recovery,OPP
27,7,1,49,Clearance,OWN,failure,Take On,OPP
28,7,2,46,Ball touch,OWN,failure,Pass,OPP
29,7,2,67,Tackle,OWN,failure,Ball touch,OPP

4. OWN→[83]→OWN  (own team keeps ball)

,match_id,period,minute,prev_event,prev_team,outcome_83,next_event,next_team
0,3,2,96,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
1,8,1,49,Attempted Tackle,OWN,failure,End,OWN
2,10,1,33,Pass,OWN,failure,Attempted Tackle,OWN
3,13,1,3,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
4,13,2,53,Ball touch,OWN,failure,Attempted Tackle,OWN
5,13,2,65,Clearance,OWN,failure,Attempted Tackle,OWN
6,13,2,65,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
7,13,2,65,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
8,14,2,80,Ball touch,OWN,failure,Attempted Tackle,OWN
9,16,2,92,Ball touch,OWN,failure,Attempted Tackle,OWN
10,17,1,36,Ball touch,OWN,failure,Attempted Tackle,OWN
11,22,1,15,Tackle,OWN,failure,Challenge,OWN
12,25,2,79,Ball touch,OWN,failure,Challenge,OWN
13,28,2,85,Pass,OWN,failure,Attempted Tackle,OWN
14,33,1,41,Blocked Pass,OWN,failure,Attempted Tackle,OWN
15,36,1,26,Tackle,OWN,failure,Attempted Tackle,OWN
16,44,2,63,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
17,44,2,88,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
18,45,1,23,Attempted Tackle,OWN,failure,Carry,OWN
19,49,2,91,Interception,OWN,failure,Challenge,OWN
20,50,2,86,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
21,53,1,13,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
22,55,2,53,Clearance,OWN,failure,Attempted Tackle,OWN
23,55,2,53,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
24,60,1,13,Attempted Tackle,OWN,failure,Attempted Tackle,OWN
25,61,1,1,Carry,OWN,failure,Attempted Tackle,OWN
26,65,1,21,Blocked Pass,OWN,failure,Attempted Tackle,OWN
27,65,2,92,Clearance,OWN,failure,Challenge,OWN
28,67,2,56,Challenge,OWN,failure,Attempted Tackle,OWN
29,69,2,77,Attempted Tackle,OWN,failure,Attempted Tackle,OWN

In [22]:
# ── typeId 83 outcome distribution ──────────────────────────────────────────

from collections import Counter

outcome_counts = Counter()

for fp in sorted(all_files):
    try:
        data   = extract_json_from_jsonp(fp)
        events = data["liveData"]["event"]
    except Exception:
        continue

    for ev in events:
        if ev.get("typeId") == 83:
            outcome_counts[ev.get("outcome")] += 1

total = sum(outcome_counts.values())
print(f"typeId 83 — Attempted Tackle outcome distribution ({total:,} total)\n")
for outcome_val, cnt in sorted(outcome_counts.items(), key=lambda x: -x[1]):
    print(f"  {str(outcome_val):>6}  →  {cnt:>5,}  ({cnt/total*100:.1f}%)")

typeId 83 — Attempted Tackle outcome distribution (5,682 total)

       0  →  5,135  (90.4%)
       1  →    547  (9.6%)

In [23]:
# ── typeId 83: compare outcome 0 vs outcome 1 ───────────────────────────────
# Goal: find what structurally differentiates the 547 outcome=1 events
# from the expected outcome=0 majority.

from collections import defaultdict, Counter

TARGET_TYPE_ID = 83
MAX_SAMPLES    = 30

# Storage per outcome value
data_by_outcome = {0: [], 1: []}

for fp in sorted(all_files):
    try:
        raw_events = extract_json_from_jsonp(fp)["liveData"]["event"]
    except Exception:
        continue

    by_period = defaultdict(list)
    for ev in raw_events:
        by_period[ev.get("periodId", 0)].append(ev)

    for period_id, pevents in by_period.items():
        for i, ev in enumerate(pevents):
            if ev.get("typeId") != TARGET_TYPE_ID:
                continue

            outcome = ev.get("outcome")
            if outcome not in (0, 1):
                continue

            prev_ev = pevents[i - 1] if i > 0 else None
            next_ev = pevents[i + 1] if i < len(pevents) - 1 else None

            data_by_outcome[outcome].append({
                "match"       : fp.name,
                "period"      : period_id,
                "minute"      : ev.get("timeMin"),
                "x"           : ev.get("x"),
                "y"           : ev.get("y"),
                "qualifiers"  : [q.get("qualifierId") for q in ev.get("qualifier", [])],
                "qual_values" : {q.get("qualifierId"): q.get("value") for q in ev.get("qualifier", [])},
                "prev_typeId" : prev_ev.get("typeId") if prev_ev else None,
                "prev_event"  : label(prev_ev.get("typeId"), events_mapping) if prev_ev else None,
                "prev_team"   : prev_ev.get("contestantId") if prev_ev else None,
                "next_typeId" : next_ev.get("typeId") if next_ev else None,
                "next_event"  : label(next_ev.get("typeId"), events_mapping) if next_ev else None,
                "next_team"   : next_ev.get("contestantId") if next_ev else None,
                "actor_team"  : ev.get("contestantId"),
            })


# ── Compare the two groups ───────────────────────────────────────────────────
for outcome_val in (0, 1):
    samples = data_by_outcome[outcome_val]
    total   = len(samples)
    print("=" * 65)
    print(f"  outcome = {outcome_val}   ({total:,} events)")
    print("=" * 65)

    # Qualifier distribution
    all_quals = [q for s in samples for q in s["qualifiers"]]
    qual_dist = Counter(all_quals)
    print(f"\n  Qualifier IDs (top 10):")
    for qid, cnt in qual_dist.most_common(10):
        print(f"    {cnt:>4}x  qualifierId {qid}  ({cnt/total*100:.1f}%)")

    # Prev event distribution
    prev_dist = Counter(s["prev_event"] for s in samples)
    print(f"\n  Most common PREV events:")
    for ev_label, cnt in prev_dist.most_common(5):
        print(f"    {cnt:>4}x  {ev_label}  ({cnt/total*100:.1f}%)")

    # Next event distribution
    next_dist = Counter(s["next_event"] for s in samples)
    print(f"\n  Most common NEXT events:")
    for ev_label, cnt in next_dist.most_common(5):
        print(f"    {cnt:>4}x  {ev_label}  ({cnt/total*100:.1f}%)")

    # Possession flow (same logic as before)
    poss_dist = Counter()
    for s in samples:
        prev_side = ("OWN" if s["prev_team"] == s["actor_team"] else "OPP") if s["prev_team"] else None
        next_side = ("OWN" if s["next_team"] == s["actor_team"] else "OPP") if s["next_team"] else None
        if prev_side and next_side:
            poss_dist[f"{prev_side}→[83]→{next_side}"] += 1
    print(f"\n  Possession flow:")
    for flow, cnt in poss_dist.most_common():
        print(f"    {cnt:>4}x  {flow}  ({cnt/total*100:.1f}%)")

    # Pitch zone (x coordinate bucket)
    xs = [s["x"] for s in samples if s["x"] is not None]
    if xs:
        import numpy as np
        print(f"\n  X coordinate (pitch position):")
        print(f"    mean={np.mean(xs):.1f}  median={np.median(xs):.1f}  "
              f"min={np.min(xs):.1f}  max={np.max(xs):.1f}")

    # Sample rows
    print(f"\n  Sample rows (up to {MAX_SAMPLES}):")
    display(
        pd.DataFrame(samples[:MAX_SAMPLES])[[
            "match", "period", "minute", "x", "y",
            "qualifiers", "prev_event", "next_event"
        ]]
    )
    print()

=================================================================
  outcome = 0   (5,135 events)
=================================================================

  Qualifier IDs (top 10):
    5135x  qualifierId 399  (100.0%)
       1x  qualifierId 189  (0.0%)

  Most common PREV events:
    3157x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})  (61.5%)
     541x  49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})  (10.5%)
     344x  83 (???)  (6.7%)
     276x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})  (5.4%)
     205x  7 ({'name': 'Tackle', 'description': 'Tackle = dispossesses an opponent of the ball - Outcome 1 = win & retain possession or out of play, 0 = win tackle but not possession'})  (4.0%)

  Most common NEXT events:
    2624x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})  (51.1%)
     650x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})  (12.7%)
     427x  3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})  (8.3%)
     341x  83 (???)  (6.6%)
     333x  50 ({'name': 'Dispossessed', 'description': 'Player is successfully tackled and loses possession of the ball'})  (6.5%)

  Possession flow:
    3656x  OPP→[83]→OPP  (71.2%)
     983x  OWN→[83]→OPP  (19.1%)
     390x  OPP→[83]→OWN  (7.6%)
     106x  OWN→[83]→OWN  (2.1%)

  X coordinate (pitch position):
    mean=42.2  median=38.9  min=1.0  max=98.4

  Sample rows (up to 30):

,match,period,minute,x,y,qualifiers,prev_event,next_event
0,10d1132abu0fa9xolj05top3o,1,2,6.8,10.3,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","61 ({'name': 'Ball touch', 'description': 'Use..."
1,10d1132abu0fa9xolj05top3o,1,3,92.2,1.9,[399],"49 ({'name': 'Ball recovery', 'description': '...",83 (???)
2,10d1132abu0fa9xolj05top3o,1,3,94.4,1.2,[399],83 (???),"61 ({'name': 'Ball touch', 'description': 'Use..."
3,10d1132abu0fa9xolj05top3o,1,7,41.5,17.7,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
4,10d1132abu0fa9xolj05top3o,1,10,57.5,15.0,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
5,10d1132abu0fa9xolj05top3o,1,19,45.0,64.9,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
6,10d1132abu0fa9xolj05top3o,1,19,14.8,68.1,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","3 ({'name': 'Take On', 'description': 'Attempt..."
7,10d1132abu0fa9xolj05top3o,1,20,43.1,56.4,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
8,10d1132abu0fa9xolj05top3o,1,35,77.2,28.0,[399],"43 ({'name': 'Deleted event', 'description': '...","1 ({'name': 'Pass', 'description': 'Any pass a..."
9,10d1132abu0fa9xolj05top3o,1,45,54.1,14.7,[399],"49 ({'name': 'Ball recovery', 'description': '...","1 ({'name': 'Pass', 'description': 'Any pass a..."
10,10d1132abu0fa9xolj05top3o,1,46,43.2,4.2,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
11,10d1132abu0fa9xolj05top3o,2,50,59.0,9.3,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","50 ({'name': 'Dispossessed', 'description': 'P..."
12,10d1132abu0fa9xolj05top3o,2,50,54.5,9.3,[399],"49 ({'name': 'Ball recovery', 'description': '...","1 ({'name': 'Pass', 'description': 'Any pass a..."
13,10d1132abu0fa9xolj05top3o,2,57,59.7,8.5,[399],"49 ({'name': 'Ball recovery', 'description': '...","3 ({'name': 'Take On', 'description': 'Attempt..."
14,10d1132abu0fa9xolj05top3o,2,66,34.7,31.2,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","3 ({'name': 'Take On', 'description': 'Attempt..."
15,10d1132abu0fa9xolj05top3o,2,81,60.0,86.5,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
16,10d1132abu0fa9xolj05top3o,2,82,31.2,40.7,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
17,10d1132abu0fa9xolj05top3o,2,84,24.1,8.4,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
18,10d1132abu0fa9xolj05top3o,2,87,24.1,33.4,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","4 ({'name': 'Foul', 'description': 'This event..."
19,10qg7chtpoj0knqnvx2oduot0,1,1,35.2,21.7,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
20,10qg7chtpoj0knqnvx2oduot0,1,7,45.9,69.7,[399],"12 ({'name': 'Clearance', 'description': 'Play...","1 ({'name': 'Pass', 'description': 'Any pass a..."
21,10qg7chtpoj0knqnvx2oduot0,1,8,80.1,6.8,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
22,10qg7chtpoj0knqnvx2oduot0,1,21,63.2,31.3,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...",83 (???)
23,10qg7chtpoj0knqnvx2oduot0,1,21,59.0,42.6,[399],83 (???),"1 ({'name': 'Pass', 'description': 'Any pass a..."
24,10qg7chtpoj0knqnvx2oduot0,1,25,47.4,78.5,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","61 ({'name': 'Ball touch', 'description': 'Use..."
25,10qg7chtpoj0knqnvx2oduot0,1,27,37.4,13.5,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
26,10qg7chtpoj0knqnvx2oduot0,1,28,22.0,45.2,[399],"49 ({'name': 'Ball recovery', 'description': '...","50 ({'name': 'Dispossessed', 'description': 'P..."
27,10qg7chtpoj0knqnvx2oduot0,1,33,56.1,48.7,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
28,10qg7chtpoj0knqnvx2oduot0,1,35,50.6,75.6,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","61 ({'name': 'Ball touch', 'description': 'Use..."
29,10qg7chtpoj0knqnvx2oduot0,1,45,30.2,85.8,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","50 ({'name': 'Dispossessed', 'description': 'P..."

=================================================================
  outcome = 1   (547 events)
=================================================================

  Qualifier IDs (top 10):
     547x  qualifierId 399  (100.0%)

  Most common PREV events:
     349x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})  (63.8%)
      49x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})  (9.0%)
      43x  49 ({'name': 'Ball recovery', 'description': 'Team wins the possession of the ball and successfully keeps possession for at least two passes or an attacking play'})  (7.9%)
      24x  83 (???)  (4.4%)
      22x  43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})  (4.0%)

  Most common NEXT events:
     262x  1 ({'name': 'Pass', 'description': 'Any pass attempted from one player to another  free kicks, corners, throw ins, goal kicks and goal assists'})  (47.9%)
     119x  61 ({'name': 'Ball touch', 'description': 'Used when a player makes a bad touch on the ball and loses possession. Outcome 1  ball simply hit the player unintentionally. Outcome 0  Player unsuccessfully controlled the ball.'})  (21.8%)
      36x  3 ({'name': 'Take On', 'description': 'Attempted dribble past an opponent (excluding when qualifier 211 is present as this is overrun and is not always a duel event)'})  (6.6%)
      27x  43 ({'name': 'Deleted event', 'description': 'Event has been deleted  the event will remain as it was originally with the same ID but will be resent with the type altered to 43.'})  (4.9%)
      27x  83 (???)  (4.9%)

  Possession flow:
     387x  OPP→[83]→OPP  (70.7%)
     109x  OWN→[83]→OPP  (19.9%)
      42x  OPP→[83]→OWN  (7.7%)
       9x  OWN→[83]→OWN  (1.6%)

  X coordinate (pitch position):
    mean=43.3  median=39.7  min=2.1  max=98.2

  Sample rows (up to 30):

,match,period,minute,x,y,qualifiers,prev_event,next_event
0,10d1132abu0fa9xolj05top3o,1,7,54.9,47.1,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
1,10d1132abu0fa9xolj05top3o,2,72,60.1,84.7,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
2,10d1132abu0fa9xolj05top3o,2,82,66.6,51.1,[399],"43 ({'name': 'Deleted event', 'description': '...","1 ({'name': 'Pass', 'description': 'Any pass a..."
3,10d1132abu0fa9xolj05top3o,2,90,55.2,82.2,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","43 ({'name': 'Deleted event', 'description': '..."
4,10qg7chtpoj0knqnvx2oduot0,1,28,93.0,18.2,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
5,10qg7chtpoj0knqnvx2oduot0,1,45,10.6,39.0,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","13 ({'name': 'Miss', 'description': 'Any shot ..."
6,10qg7chtpoj0knqnvx2oduot0,2,54,38.6,39.2,[399],"61 ({'name': 'Ball touch', 'description': 'Use...","61 ({'name': 'Ball touch', 'description': 'Use..."
7,10qg7chtpoj0knqnvx2oduot0,2,74,63.7,72.9,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
8,113wccwt50kebz0thqf0fxkpg,2,57,66.5,55.9,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
9,113wccwt50kebz0thqf0fxkpg,2,91,45.8,85.9,[399],83 (???),"3 ({'name': 'Take On', 'description': 'Attempt..."
10,11hplskmrac4dwfmqv72f9nh0,1,9,13.4,18.4,[399],"61 ({'name': 'Ball touch', 'description': 'Use...","61 ({'name': 'Ball touch', 'description': 'Use..."
11,11hplskmrac4dwfmqv72f9nh0,1,14,66.5,83.6,[399],"8 ({'name': 'Interception', 'description': 'Wh...","43 ({'name': 'Deleted event', 'description': '..."
12,11hplskmrac4dwfmqv72f9nh0,2,86,33.3,76.4,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
13,1288ajju0cadnuxxhvkal1mok,1,24,79.1,90.7,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","43 ({'name': 'Deleted event', 'description': '..."
14,1288ajju0cadnuxxhvkal1mok,1,35,25.4,68.3,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","61 ({'name': 'Ball touch', 'description': 'Use..."
15,1288ajju0cadnuxxhvkal1mok,2,47,15.5,30.3,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
16,1288ajju0cadnuxxhvkal1mok,2,78,78.5,95.7,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","61 ({'name': 'Ball touch', 'description': 'Use..."
17,1288ajju0cadnuxxhvkal1mok,2,84,76.4,29.5,[399],"49 ({'name': 'Ball recovery', 'description': '...","43 ({'name': 'Deleted event', 'description': '..."
18,1288ajju0cadnuxxhvkal1mok,2,91,64.4,74.7,[399],"49 ({'name': 'Ball recovery', 'description': '...","1 ({'name': 'Pass', 'description': 'Any pass a..."
19,12zi2fz6nuyhye00alaymbms4,1,12,22.8,41.1,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","61 ({'name': 'Ball touch', 'description': 'Use..."
20,12zi2fz6nuyhye00alaymbms4,2,52,42.1,32.4,[399],"3 ({'name': 'Take On', 'description': 'Attempt...","1 ({'name': 'Pass', 'description': 'Any pass a..."
21,13d50vdn5ecuddcpg1cvdrq50,2,61,32.3,89.0,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","50 ({'name': 'Dispossessed', 'description': 'P..."
22,13qwzalezgy8gxih0ube0ap78,1,0,68.1,25.9,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
23,13qwzalezgy8gxih0ube0ap78,1,42,42.4,19.0,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
24,13qwzalezgy8gxih0ube0ap78,2,74,9.4,30.3,[399],"43 ({'name': 'Deleted event', 'description': '...","15 ({'name': 'Attempt Saved', 'description': '..."
25,13qwzalezgy8gxih0ube0ap78,2,83,63.1,4.0,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
26,144g7b7ez101gt3yczm0yblzo,1,39,34.9,73.5,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","1 ({'name': 'Pass', 'description': 'Any pass a..."
27,144g7b7ez101gt3yczm0yblzo,2,73,32.3,68.0,[399],"49 ({'name': 'Ball recovery', 'description': '...","1 ({'name': 'Pass', 'description': 'Any pass a..."
28,14ia91hr21lnjto1f2uga5f6c,1,24,23.7,20.2,[399],"3 ({'name': 'Take On', 'description': 'Attempt...","45 ({'name': 'Challenge', 'description': 'When..."
29,14ia91hr21lnjto1f2uga5f6c,2,81,49.6,95.0,[399],"1 ({'name': 'Pass', 'description': 'Any pass a...","61 ({'name': 'Ball touch', 'description': 'Use..."